<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_SuluAdmin_UpdateBuildCommand_LazyService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private '.sulu_admin.update_build_command.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.sulu_admin.update_build_command.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sulu:admin:update-build', [], 'Updates the administration application JavaScript build by downloading the official build from the sulu/skeleton repository or building the assets via npm.', false, #[\Closure(name: 'sulu_admin.update_build_command', class: 'Sulu\\Bundle\\AdminBundle\\Command\\UpdateBuildCommand')] fn (): \Sulu\Bundle\AdminBundle\Command\UpdateBuildCommand => ($container->privates['sulu_admin.update_build_command'] ?? $container->load('getSuluAdmin_UpdateBuildCommandService')));
    }
}
