<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_SuluMedia_Command_Init_LazyService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private '.sulu_media.command.init.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.sulu_media.command.init.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sulu:media:init', [], 'Init Sulu Media Bundle', false, #[\Closure(name: 'sulu_media.command.init', class: 'Sulu\\Bundle\\MediaBundle\\Command\\InitCommand')] fn (): \Sulu\Bundle\MediaBundle\Command\InitCommand => ($container->privates['sulu_media.command.init'] ?? $container->load('getSuluMedia_Command_InitService')));
    }
}
