<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MklIyIqService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.mklIyIq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mklIyIq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contacts' => ['privates', 'sulu_contact.contact_smart_content_provider', 'getSuluContact_ContactSmartContentProviderService', true],
            'accounts' => ['privates', 'sulu_contact.account_smart_content_provider', 'getSuluContact_AccountSmartContentProviderService', true],
            'media' => ['privates', 'sulu_media.media_smart_content_provider', 'getSuluMedia_MediaSmartContentProviderService', true],
            'pages' => ['privates', 'sulu_page.page_smart_content_provider', 'getSuluPage_PageSmartContentProviderService', true],
            'events' => ['privates', 'sulu_event.event_smart_content_provider', 'getSuluEvent_EventSmartContentProviderService', true],
        ], [
            'contacts' => 'Sulu\\Bundle\\ContactBundle\\Infrastructure\\Sulu\\Content\\SmartContent\\ContactSmartContentProvider',
            'accounts' => 'Sulu\\Bundle\\ContactBundle\\Infrastructure\\Sulu\\Content\\SmartContent\\AccountSmartContentProvider',
            'media' => 'Sulu\\Bundle\\MediaBundle\\Infrastructure\\Sulu\\Content\\SmartContent\\MediaSmartContentProvider',
            'pages' => 'Sulu\\Page\\Infrastructure\\Sulu\\Content\\PageSmartContentProvider',
            'events' => 'Manuxi\\SuluEventBundle\\Content\\EventSmartContentProvider',
        ]);
    }
}
