<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_SuluMedia_Command_FormatCache_Regenerate_LazyService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private '.sulu_media.command.format_cache.regenerate.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.sulu_media.command.format_cache.regenerate.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sulu:media:regenerate-formats', [], 'Loops over sulu image cache, and regenerates the existing images', false, #[\Closure(name: 'sulu_media.command.format_cache.regenerate', class: 'Sulu\\Bundle\\MediaBundle\\Command\\FormatCacheRegenerateCommand')] fn (): \Sulu\Bundle\MediaBundle\Command\FormatCacheRegenerateCommand => ($container->privates['sulu_media.command.format_cache.regenerate'] ?? $container->load('getSuluMedia_Command_FormatCache_RegenerateService')));
    }
}
