<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_Y6tzohaService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.Y6tzoha' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_page.remove_page_translation_handler'] ?? $container->load('getSuluPage_RemovePageTranslationHandlerService'));

        if (isset($container->privates['.messenger.handler_descriptor.Y6tzoha'])) {
            return $container->privates['.messenger.handler_descriptor.Y6tzoha'];
        }

        return $container->privates['.messenger.handler_descriptor.Y6tzoha'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor($a, []);
    }
}
