<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_41p9IZ4Service extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.41p9IZ4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.41p9IZ4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sulu_content.content_controller::indexAction' => ['privates', '.service_locator.ss1NsTA.sulu_content.content_controller::indexAction()', 'get_ServiceLocator_Ss1NsTA_SuluContent_ContentControllerindexActionService', true],
            'Sulu\\Content\\UserInterface\\Controller\\Website\\ContentController::indexAction' => ['privates', '.service_locator.ss1NsTA.sulu_content.content_controller::indexAction()', 'get_ServiceLocator_Ss1NsTA_SuluContent_ContentControllerindexActionService', true],
            'Manuxi\\SuluEventBundle\\Controller\\Admin\\EventController::setViewHandler' => ['privates', '.service_locator.g2zSUIo.Manuxi\\SuluEventBundle\\Controller\\Admin\\EventController::setViewHandler()', 'getEventControllersetViewHandlerService', true],
            'Manuxi\\SuluEventBundle\\Controller\\Admin\\LocationController::setViewHandler' => ['privates', '.service_locator.g2zSUIo.Manuxi\\SuluEventBundle\\Controller\\Admin\\LocationController::setViewHandler()', 'getLocationControllersetViewHandlerService', true],
            'Manuxi\\SuluEventBundle\\Controller\\Admin\\SettingsController::setViewHandler' => ['privates', '.service_locator.g2zSUIo.Manuxi\\SuluEventBundle\\Controller\\Admin\\SettingsController::setViewHandler()', 'getSettingsControllersetViewHandlerService', true],
            'sulu_content.content_controller:indexAction' => ['privates', '.service_locator.ss1NsTA.sulu_content.content_controller::indexAction()', 'get_ServiceLocator_Ss1NsTA_SuluContent_ContentControllerindexActionService', true],
            'Manuxi\\SuluEventBundle\\Controller\\Admin\\EventController:setViewHandler' => ['privates', '.service_locator.g2zSUIo.Manuxi\\SuluEventBundle\\Controller\\Admin\\EventController::setViewHandler()', 'getEventControllersetViewHandlerService', true],
            'Manuxi\\SuluEventBundle\\Controller\\Admin\\LocationController:setViewHandler' => ['privates', '.service_locator.g2zSUIo.Manuxi\\SuluEventBundle\\Controller\\Admin\\LocationController::setViewHandler()', 'getLocationControllersetViewHandlerService', true],
            'Manuxi\\SuluEventBundle\\Controller\\Admin\\SettingsController:setViewHandler' => ['privates', '.service_locator.g2zSUIo.Manuxi\\SuluEventBundle\\Controller\\Admin\\SettingsController::setViewHandler()', 'getSettingsControllersetViewHandlerService', true],
        ], [
            'sulu_content.content_controller::indexAction' => '?',
            'Sulu\\Content\\UserInterface\\Controller\\Website\\ContentController::indexAction' => '?',
            'Manuxi\\SuluEventBundle\\Controller\\Admin\\EventController::setViewHandler' => '?',
            'Manuxi\\SuluEventBundle\\Controller\\Admin\\LocationController::setViewHandler' => '?',
            'Manuxi\\SuluEventBundle\\Controller\\Admin\\SettingsController::setViewHandler' => '?',
            'sulu_content.content_controller:indexAction' => '?',
            'Manuxi\\SuluEventBundle\\Controller\\Admin\\EventController:setViewHandler' => '?',
            'Manuxi\\SuluEventBundle\\Controller\\Admin\\LocationController:setViewHandler' => '?',
            'Manuxi\\SuluEventBundle\\Controller\\Admin\\SettingsController:setViewHandler' => '?',
        ]);
    }
}
