<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_SuluSecurity_Command_CreateRole_LazyService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private '.sulu_security.command.create_role.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.sulu_security.command.create_role.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sulu:security:role:create', [], 'Create a role.', false, #[\Closure(name: 'sulu_security.command.create_role', class: 'Sulu\\Bundle\\SecurityBundle\\Command\\CreateRoleCommand')] fn (): \Sulu\Bundle\SecurityBundle\Command\CreateRoleCommand => ($container->privates['sulu_security.command.create_role'] ?? $container->load('getSuluSecurity_Command_CreateRoleService')));
    }
}
