<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_JDBg8K4Service extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.jDBg8K4' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['mailer.messenger.message_handler'] ?? $container->load('getMailer_Messenger_MessageHandlerService'));

        if (isset($container->privates['.messenger.handler_descriptor.jDBg8K4'])) {
            return $container->privates['.messenger.handler_descriptor.jDBg8K4'];
        }

        return $container->privates['.messenger.handler_descriptor.jDBg8K4'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor($a, []);
    }
}
