<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_KvVZ73kService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.kvVZ73k' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.kvVZ73k'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->privates['http_client.messenger.ping_webhook_handler'] ?? $container->load('getHttpClient_Messenger_PingWebhookHandlerService')), []);
    }
}
