<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_CmsigSeal_IndexDropCommand_LazyService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private '.cmsig_seal.index_drop_command.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.cmsig_seal.index_drop_command.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('cmsig:seal:index-drop', [], 'Drop configured search indexes.', false, #[\Closure(name: 'cmsig_seal.index_drop_command', class: 'CmsIg\\Seal\\Integration\\Symfony\\Command\\IndexDropCommand')] fn (): \CmsIg\Seal\Integration\Symfony\Command\IndexDropCommand => ($container->privates['cmsig_seal.index_drop_command'] ?? $container->load('getCmsigSeal_IndexDropCommandService')));
    }
}
