<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_SuluMedia_Command_TypeUpdate_LazyService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private '.sulu_media.command.type_update.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.sulu_media.command.type_update.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sulu:media:type:update', [], 'Update all media type by the set configuration', false, #[\Closure(name: 'sulu_media.command.type_update', class: 'Sulu\\Bundle\\MediaBundle\\Command\\MediaTypeUpdateCommand')] fn (): \Sulu\Bundle\MediaBundle\Command\MediaTypeUpdateCommand => ($container->privates['sulu_media.command.type_update'] ?? $container->load('getSuluMedia_Command_TypeUpdateService')));
    }
}
