<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAutoAuthorDataMapperService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Manuxi\SuluEventBundle\Content\DataMapper\AutoAuthorDataMapper' shared service.
     *
     * @return \Manuxi\SuluEventBundle\Content\DataMapper\AutoAuthorDataMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container));

        if (isset($container->privates['Manuxi\\SuluEventBundle\\Content\\DataMapper\\AutoAuthorDataMapper'])) {
            return $container->privates['Manuxi\\SuluEventBundle\\Content\\DataMapper\\AutoAuthorDataMapper'];
        }

        return $container->privates['Manuxi\\SuluEventBundle\\Content\\DataMapper\\AutoAuthorDataMapper'] = new \Manuxi\SuluEventBundle\Content\DataMapper\AutoAuthorDataMapper($a);
    }
}
