<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCmsigSeal_IndexDropCommandService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'cmsig_seal.index_drop_command' shared service.
     *
     * @return \CmsIg\Seal\Integration\Symfony\Command\IndexDropCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['cmsig_seal.index_drop_command'] = $instance = new \CmsIg\Seal\Integration\Symfony\Command\IndexDropCommand(($container->privates['cmsig_seal.engine_registry'] ?? $container->load('getCmsigSeal_EngineRegistryService')));

        $instance->setName('cmsig:seal:index-drop');
        $instance->setDescription('Drop configured search indexes.');

        return $instance;
    }
}
