<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCmsigSeal_ReindexCommandService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'cmsig_seal.reindex_command' shared service.
     *
     * @return \CmsIg\Seal\Integration\Symfony\Command\ReindexCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['cmsig_seal.reindex_command'] = $instance = new \CmsIg\Seal\Integration\Symfony\Command\ReindexCommand(($container->privates['cmsig_seal.engine_registry'] ?? $container->load('getCmsigSeal_EngineRegistryService')), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['sulu_contact.admin_account_reindex_provider'] ?? $container->load('getSuluContact_AdminAccountReindexProviderService'));
            yield 1 => ($container->privates['sulu_contact.admin_contact_reindex_provider'] ?? $container->load('getSuluContact_AdminContactReindexProviderService'));
            yield 2 => ($container->privates['sulu_media.admin_media_reindex_provider'] ?? $container->load('getSuluMedia_AdminMediaReindexProviderService'));
            yield 3 => ($container->privates['sulu_media.admin_collection_reindex_provider'] ?? $container->load('getSuluMedia_AdminCollectionReindexProviderService'));
            yield 4 => ($container->privates['sulu_category.admin_category_reindex_provider'] ?? $container->load('getSuluCategory_AdminCategoryReindexProviderService'));
            yield 5 => ($container->privates['sulu_page.admin_page_reindex_provider'] ?? $container->load('getSuluPage_AdminPageReindexProviderService'));
            yield 6 => ($container->privates['sulu_page.website_page_reindex_provider'] ?? $container->load('getSuluPage_WebsitePageReindexProviderService'));
            yield 7 => ($container->privates['sulu_event.search.admin_provider'] ?? $container->load('getSuluEvent_Search_AdminProviderService'));
            yield 8 => ($container->privates['sulu_event.search.website_provider'] ?? $container->load('getSuluEvent_Search_WebsiteProviderService'));
        }, 9));

        $instance->setName('cmsig:seal:reindex');
        $instance->setDescription('Reindex configured search indexes.');

        return $instance;
    }
}
