<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomUrlRouteRepositoryInterfaceService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sulu\CustomUrl\Domain\Repository\CustomUrlRouteRepositoryInterface' shared service.
     *
     * @return \Sulu\CustomUrl\Infrastructure\Doctrine\Repository\CustomUrlRouteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['Sulu\\CustomUrl\\Domain\\Repository\\CustomUrlRouteRepositoryInterface'])) {
            return $container->services['Sulu\\CustomUrl\\Domain\\Repository\\CustomUrlRouteRepositoryInterface'];
        }

        return $container->services['Sulu\\CustomUrl\\Domain\\Repository\\CustomUrlRouteRepositoryInterface'] = new \Sulu\CustomUrl\Infrastructure\Doctrine\Repository\CustomUrlRouteRepository($a);
    }
}
