<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCmsigSeal_Engine_DefaultService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'cmsig_seal.engine.default' shared service.
     *
     * @return \CmsIg\Seal\Engine
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['cmsig_seal.engine.default'] = new \CmsIg\Seal\Engine(($container->privates['cmsig_seal.adapter.default'] ?? $container->load('getCmsigSeal_Adapter_DefaultService')), ($container->privates['cmsig_seal.schema.default'] ?? $container->load('getCmsigSeal_Schema_DefaultService')));
    }
}
