<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomUrlRepositoryInterfaceService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Sulu\CustomUrl\Domain\Repository\CustomUrlRepositoryInterface' shared service.
     *
     * @return \Sulu\CustomUrl\Infrastructure\Doctrine\Repository\CustomUrlRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['Sulu\\CustomUrl\\Domain\\Repository\\CustomUrlRepositoryInterface'])) {
            return $container->privates['Sulu\\CustomUrl\\Domain\\Repository\\CustomUrlRepositoryInterface'];
        }

        return $container->privates['Sulu\\CustomUrl\\Domain\\Repository\\CustomUrlRepositoryInterface'] = new \Sulu\CustomUrl\Infrastructure\Doctrine\Repository\CustomUrlRepository($a);
    }
}
