<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_CachePoolInvalidateTagsService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'console.command.cache_pool_invalidate_tags' shared service.
     *
     * @return \Symfony\Bundle\FrameworkBundle\Command\CachePoolInvalidateTagsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['console.command.cache_pool_invalidate_tags'] = $instance = new \Symfony\Bundle\FrameworkBundle\Command\CachePoolInvalidateTagsCommand(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cache.app' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'sulu_preview.preview.cache' => ['privates', '.sulu_preview.preview.cache.taggable', 'get_SuluPreview_Preview_Cache_TaggableService', true],
            'sulu_admin.collaboration_cache' => ['privates', '.sulu_admin.collaboration_cache.taggable', 'get_SuluAdmin_CollaborationCache_TaggableService', true],
            'sulu_admin.icon_cache' => ['privates', '.sulu_admin.icon_cache.taggable', 'get_SuluAdmin_IconCache_TaggableService', true],
        ], [
            'cache.app' => 'Symfony\\Component\\Cache\\Adapter\\TagAwareAdapter',
            'sulu_preview.preview.cache' => 'Symfony\\Component\\Cache\\Adapter\\TagAwareAdapter',
            'sulu_admin.collaboration_cache' => 'Symfony\\Component\\Cache\\Adapter\\TagAwareAdapter',
            'sulu_admin.icon_cache' => 'Symfony\\Component\\Cache\\Adapter\\TagAwareAdapter',
        ]));

        $instance->setName('cache:pool:invalidate-tags');
        $instance->setDescription('Invalidate cache tags for all or a specific pool');

        return $instance;
    }
}
