<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCmsigSeal_EngineRegistryService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'cmsig_seal.engine_registry' shared service.
     *
     * @return \CmsIg\Seal\EngineRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['cmsig_seal.engine_registry'] = new \CmsIg\Seal\EngineRegistry(new RewindableGenerator(function () use ($container) {
            yield 'default' => ($container->privates['cmsig_seal.engine.default'] ?? $container->load('getCmsigSeal_Engine_DefaultService'));
        }, 1));
    }
}
