<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_Listeners_ResolveTargetEntityService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'doctrine.orm.listeners.resolve_target_entity' shared service.
     *
     * @return \Doctrine\ORM\Tools\ResolveTargetEntityListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['doctrine.orm.listeners.resolve_target_entity'] = $instance = new \Doctrine\ORM\Tools\ResolveTargetEntityListener();

        $instance->addResolveTargetEntity('Sulu\\Bundle\\ContactBundle\\Entity\\ContactInterface', 'Sulu\\Bundle\\ContactBundle\\Entity\\Contact', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\ContactBundle\\Entity\\AccountInterface', 'Sulu\\Bundle\\ContactBundle\\Entity\\Account', []);
        $instance->addResolveTargetEntity('Sulu\\Component\\Security\\Authentication\\UserInterface', 'Sulu\\Bundle\\SecurityBundle\\Entity\\User', []);
        $instance->addResolveTargetEntity('Sulu\\Component\\Security\\Authentication\\RoleInterface', 'Sulu\\Bundle\\SecurityBundle\\Entity\\Role', []);
        $instance->addResolveTargetEntity('Sulu\\Component\\Security\\Authentication\\RoleSettingInterface', 'Sulu\\Bundle\\SecurityBundle\\Entity\\RoleSetting', []);
        $instance->addResolveTargetEntity('Sulu\\Component\\Security\\Authorization\\AccessControl\\AccessControlInterface', 'Sulu\\Bundle\\SecurityBundle\\Entity\\AccessControl', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\WebsiteBundle\\Entity\\AnalyticsInterface', 'Sulu\\Bundle\\WebsiteBundle\\Entity\\Analytics', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\TagBundle\\Tag\\TagInterface', 'Sulu\\Bundle\\TagBundle\\Entity\\Tag', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\MediaBundle\\Entity\\MediaInterface', 'Sulu\\Bundle\\MediaBundle\\Entity\\Media', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\MediaBundle\\Entity\\CollectionInterface', 'Sulu\\Bundle\\MediaBundle\\Entity\\Collection', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\CategoryBundle\\Entity\\CategoryInterface', 'Sulu\\Bundle\\CategoryBundle\\Entity\\Category', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\CategoryBundle\\Entity\\CategoryTranslationInterface', 'Sulu\\Bundle\\CategoryBundle\\Entity\\CategoryTranslation', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\CategoryBundle\\Entity\\KeywordInterface', 'Sulu\\Bundle\\CategoryBundle\\Entity\\Keyword', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\ActivityInterface', 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity', []);
        $instance->addResolveTargetEntity('Sulu\\CustomUrl\\Domain\\Model\\CustomUrlInterface', 'Sulu\\CustomUrl\\Domain\\Model\\CustomUrl', []);
        $instance->addResolveTargetEntity('Sulu\\CustomUrl\\Domain\\Model\\CustomUrlRouteInterface', 'Sulu\\CustomUrl\\Domain\\Model\\CustomUrlRoute', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\PreviewBundle\\Domain\\Model\\PreviewLinkInterface', 'Sulu\\Bundle\\PreviewBundle\\Domain\\Model\\PreviewLink', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\AudienceTargetingBundle\\Entity\\TargetGroupInterface', 'Sulu\\Bundle\\AudienceTargetingBundle\\Entity\\TargetGroup', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\AudienceTargetingBundle\\Entity\\TargetGroupConditionInterface', 'Sulu\\Bundle\\AudienceTargetingBundle\\Entity\\TargetGroupCondition', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\AudienceTargetingBundle\\Entity\\TargetGroupRuleInterface', 'Sulu\\Bundle\\AudienceTargetingBundle\\Entity\\TargetGroupRule', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\AudienceTargetingBundle\\Entity\\TargetGroupWebspaceInterface', 'Sulu\\Bundle\\AudienceTargetingBundle\\Entity\\TargetGroupWebspace', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\TrashBundle\\Domain\\Model\\TrashItemInterface', 'Sulu\\Bundle\\TrashBundle\\Domain\\Model\\TrashItem', []);
        $instance->addResolveTargetEntity('Sulu\\Bundle\\ReferenceBundle\\Domain\\Model\\ReferenceInterface', 'Sulu\\Bundle\\ReferenceBundle\\Domain\\Model\\Reference', []);
        $instance->addResolveTargetEntity('Sulu\\Page\\Domain\\Model\\PageInterface', 'Sulu\\Page\\Domain\\Model\\Page', []);
        $instance->addResolveTargetEntity('Sulu\\Page\\Domain\\Model\\PageDimensionContentInterface', 'Sulu\\Page\\Domain\\Model\\PageDimensionContent', []);

        return $instance;
    }
}
