<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_Security_Authenticator_HttpBasic_TestService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'debug.security.authenticator.http_basic.test' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.authenticator.http_basic.test'] ?? $container->load('getSecurity_Authenticator_HttpBasic_TestService'));

        if (isset($container->privates['debug.security.authenticator.http_basic.test'])) {
            return $container->privates['debug.security.authenticator.http_basic.test'];
        }

        return $container->privates['debug.security.authenticator.http_basic.test'] = new \Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticator($a);
    }
}
