<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventDimensionContentRepositoryService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Manuxi\SuluEventBundle\Repository\EventDimensionContentRepository' shared service.
     *
     * @return \Manuxi\SuluEventBundle\Repository\EventDimensionContentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Manuxi\\SuluEventBundle\\Repository\\EventDimensionContentRepository'] = new \Manuxi\SuluEventBundle\Repository\EventDimensionContentRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
