<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosRest_ViewHandlerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'fos_rest.view_handler' shared service.
     *
     * @return \FOS\RestBundle\View\ViewHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['fos_rest.serializer.jms'] ?? $container->load('getFosRest_Serializer_JmsService'));

        if (isset($container->services['fos_rest.view_handler'])) {
            return $container->services['fos_rest.view_handler'];
        }

        $container->services['fos_rest.view_handler'] = $instance = \FOS\RestBundle\View\ViewHandler::create(($container->services['router'] ?? self::getRouterService($container)), $a, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ['json' => false, 'csv' => false], 400, 204, false, ['serializeNullStrategy' => true]);

        $instance->registerHandler('csv', [($container->privates['sulu_core.rest.view_handler.csv'] ?? $container->load('getSuluCore_Rest_ViewHandler_CsvService')), 'createResponse']);

        return $instance;
    }
}
