<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosJsRouting_DumpCommandService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'fos_js_routing.dump_command' shared service.
     *
     * @return \FOS\JsRoutingBundle\Command\DumpCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['fos_js_routing.dump_command'] = $instance = new \FOS\JsRoutingBundle\Command\DumpCommand(($container->services['fos_js_routing.routes_response'] ??= new \FOS\JsRoutingBundle\Response\RoutesResponse()), ($container->services['fos_js_routing.extractor'] ?? $container->load('getFosJsRouting_ExtractorService')), ($container->services['fos_js_routing.serializer'] ?? $container->load('getFosJsRouting_SerializerService')), \dirname(__DIR__, 5), NULL);

        $instance->setName('fos:js-routing:dump');
        $instance->setDescription('Dumps exposed routes to the filesystem');

        return $instance;
    }
}
