<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosJsRouting_ControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'fos_js_routing.controller' shared service.
     *
     * @return \FOS\JsRoutingBundle\Controller\Controller
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['fos_js_routing.controller'] = new \FOS\JsRoutingBundle\Controller\Controller(($container->services['fos_js_routing.routes_response'] ??= new \FOS\JsRoutingBundle\Response\RoutesResponse()), ($container->services['fos_js_routing.serializer'] ?? $container->load('getFosJsRouting_SerializerService')), ($container->services['fos_js_routing.extractor'] ?? $container->load('getFosJsRouting_ExtractorService')), $container->parameters['fos_js_routing.cache_control'], true);
    }
}
