<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHtmlSanitizer_Config_DefaultService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'html_sanitizer.config.default' shared service.
     *
     * @return \Symfony\Component\HtmlSanitizer\HtmlSanitizerConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\HtmlSanitizer\HtmlSanitizerConfig();

        $container->privates['html_sanitizer.config.default'] = $instance = $instance->allowSafeElements();

        return $instance;
    }
}
