<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_Metadata_YamlDriverService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'jms_serializer.metadata.yaml_driver' shared service.
     *
     * @return \JMS\Serializer\Metadata\Driver\YamlDriver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['jms_serializer.metadata.yaml_driver'] = new \JMS\Serializer\Metadata\Driver\YamlDriver(($container->privates['jms_serializer.metadata.traceable_file_locator'] ?? $container->load('getJmsSerializer_Metadata_TraceableFileLocatorService')), ($container->privates['jms_serializer.identical_property_naming_strategy'] ??= new \JMS\Serializer\Naming\IdenticalPropertyNamingStrategy()), ($container->privates['jms_serializer.type_parser'] ??= new \JMS\Serializer\Type\Parser()), ($container->privates['jms_serializer.expression_evaluator'] ?? $container->load('getJmsSerializer_ExpressionEvaluatorService')));
    }
}
