<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_SymfonyUidHandlerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'jms_serializer.symfony_uid_handler' shared service.
     *
     * @return \JMS\Serializer\Handler\SymfonyUidHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['jms_serializer.symfony_uid_handler'] = new \JMS\Serializer\Handler\SymfonyUidHandler('canonical', true);
    }
}
