<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_EventDispatcherService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'jms_serializer.event_dispatcher' shared service.
     *
     * @return \JMS\SerializerBundle\Debug\TraceableEventDispatcher
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['jms_serializer.event_dispatcher.service_locator'] ?? $container->load('getJmsSerializer_EventDispatcher_ServiceLocatorService'));

        if (isset($container->privates['jms_serializer.event_dispatcher'])) {
            return $container->privates['jms_serializer.event_dispatcher'];
        }

        $container->privates['jms_serializer.event_dispatcher'] = $instance = new \JMS\SerializerBundle\Debug\TraceableEventDispatcher($a);

        $instance->addListener('serializer.pre_serialize', ['jms_serializer.traceable_runs_listener', 'saveRunInfo'], NULL, NULL, NULL);
        $instance->addListener('serializer.pre_serialize', ['jms_serializer.doctrine_proxy_subscriber', 'onPreSerializeTypedProxy'], NULL, NULL, 'Doctrine\\Persistence\\Proxy');
        $instance->addListener('serializer.pre_serialize', ['jms_serializer.doctrine_proxy_subscriber', 'onPreSerializeTypedProxy'], NULL, NULL, 'Doctrine\\Common\\Persistence\\Proxy');
        $instance->addListener('serializer.pre_serialize', ['jms_serializer.doctrine_proxy_subscriber', 'onPreSerialize'], NULL, NULL, 'Doctrine\\ORM\\PersistentCollection');
        $instance->addListener('serializer.pre_serialize', ['jms_serializer.doctrine_proxy_subscriber', 'onPreSerialize'], NULL, NULL, 'Doctrine\\ODM\\MongoDB\\PersistentCollection');
        $instance->addListener('serializer.pre_serialize', ['jms_serializer.doctrine_proxy_subscriber', 'onPreSerialize'], NULL, NULL, 'Doctrine\\ODM\\PHPCR\\PersistentCollection');
        $instance->addListener('serializer.pre_serialize', ['jms_serializer.doctrine_proxy_subscriber', 'onPreSerialize'], NULL, NULL, 'Doctrine\\Persistence\\Proxy');
        $instance->addListener('serializer.pre_serialize', ['jms_serializer.doctrine_proxy_subscriber', 'onPreSerialize'], NULL, NULL, 'Doctrine\\Common\\Persistence\\Proxy');
        $instance->addListener('serializer.pre_serialize', ['jms_serializer.doctrine_proxy_subscriber', 'onPreSerialize'], NULL, NULL, 'ProxyManager\\Proxy\\LazyLoadingInterface');
        $instance->addListener('serializer.pre_deserialize', ['jms_serializer.traceable_runs_listener', 'saveRunInfo'], NULL, NULL, NULL);
        $instance->addListener('serializer.post_serialize', ['sulu_core.representation_handler', 'onPostSerialize'], NULL, 'json', NULL);
        $instance->addListener('serializer.post_serialize', ['sulu_admin.dropdown_toolbar_action_subscriber', 'onPostSerialize'], 'Sulu\\Bundle\\AdminBundle\\Admin\\View\\DropdownToolbarAction', 'json', NULL);
        $instance->addListener('serializer.post_serialize', ['sulu_admin.item_metadata_serializer_subscriber', 'onPostSerializeFormMetadata'], 'Sulu\\Bundle\\AdminBundle\\Metadata\\FormMetadata\\FormMetadata', 'json', NULL);
        $instance->addListener('serializer.post_serialize', ['sulu_admin.item_metadata_serializer_subscriber', 'onPostSerializeItemMetadata'], 'Sulu\\Bundle\\AdminBundle\\Metadata\\FormMetadata\\ItemMetadata', 'json', NULL);
        $instance->addListener('serializer.post_serialize', ['sulu_admin.item_metadata_serializer_subscriber', 'onPostSerializeItemMetadata'], 'Sulu\\Bundle\\AdminBundle\\Metadata\\FormMetadata\\FieldMetadata', 'json', NULL);
        $instance->addListener('serializer.post_serialize', ['sulu_admin.item_metadata_serializer_subscriber', 'onPostSerializeItemMetadata'], 'Sulu\\Bundle\\AdminBundle\\Metadata\\FormMetadata\\SectionMetadata', 'json', NULL);
        $instance->addListener('serializer.post_serialize', ['sulu_admin.item_metadata_serializer_subscriber', 'onPostSerializeOptionMetadata'], 'Sulu\\Bundle\\AdminBundle\\Metadata\\FormMetadata\\OptionMetadata', 'json', NULL);
        $instance->addListener('serializer.post_serialize', ['sulu_admin.save_with_form_dialog_toolbar_action_subscriber', 'onPostSerialize'], 'Sulu\\Bundle\\AdminBundle\\Admin\\View\\SaveWithFormDialogToolbarAction', 'json', NULL);
        $instance->addListener('serializer.post_serialize', ['sulu_admin.toggler_toolbar_action_subscriber', 'onPostSerialize'], 'Sulu\\Bundle\\AdminBundle\\Admin\\View\\TogglerToolbarAction', 'json', NULL);
        $instance->addListener('serializer.post_serialize', ['sulu_security.serializer.handler.secured_entity', 'onPostSerialize'], NULL, NULL, NULL);
        $instance->addListener('serializer.post_serialize', ['sulu_website.analytics.event_subscriber', 'onPostSerialize'], NULL, 'json', NULL);
        $instance->addListener('serializer.post_serialize', ['sulu_security.serializer.media_permissions', 'onPostSerialize'], NULL, NULL, NULL);
        $instance->addListener('serializer.post_serialize', ['sulu_hash.event_subscriber.serializer', 'onPostSerialize'], NULL, NULL, NULL);
        $instance->addListener('serializer.post_serialize', ['sulu_page.webspace.serializer.event_subscriber', 'onPostSerialize'], NULL, 'json', NULL);
        $instance->addListener('serializer.post_deserialize', ['sulu_audience_targeting.serializer.target_group_subscriber', 'onPostDeserialize'], NULL, 'json', NULL);
        $instance->addListener('serializer.post_deserialize', ['sulu_audience_targeting.serializer.target_group_rule_serializer', 'onPostDeserialize'], NULL, 'json', NULL);

        return $instance;
    }
}
