<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_Metadata_TraceableFileLocator_InnerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'jms_serializer.metadata.traceable_file_locator.inner' shared service.
     *
     * @return \Metadata\Driver\FileLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['jms_serializer.metadata.traceable_file_locator.inner'] = new \Metadata\Driver\FileLocator(['Sulu\\Bundle\\AdminBundle' => 'D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\AdminBundle/Resources/config/serializer', 'Sulu\\Bundle\\CategoryBundle' => 'D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\CategoryBundle/Resources/config/serializer', 'Sulu\\Page\\Infrastructure\\Symfony\\HttpKernel' => 'D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\sulu\\sulu\\packages\\page/config/serializer', 'Sulu\\Component\\Webspace' => 'D:/Projects/Bundles/SuluEventBundle/vendor/sulu/sulu/packages/page/src/Infrastructure/Symfony/HttpKernel/../../../../config/serializer', 'Sulu\\Bundle\\CategoryBundle\\Entity' => 'D:/Projects/Bundles/SuluEventBundle/vendor/sulu/sulu/src/Sulu/Bundle/CategoryBundle/DependencyInjection/../Resources/config/serializer', 'Sulu\\Bundle\\AdminBundle\\SmartContent\\Configuration' => 'D:/Projects/Bundles/SuluEventBundle/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/DependencyInjection/../Resources/config/serializer']);
    }
}
