<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_JsonDeserializationVisitorService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'jms_serializer.json_deserialization_visitor' shared service.
     *
     * @return \JMS\Serializer\Visitor\Factory\JsonDeserializationVisitorFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['jms_serializer.json_deserialization_visitor'] = $instance = new \JMS\Serializer\Visitor\Factory\JsonDeserializationVisitorFactory(false);

        $instance->setOptions(0);

        return $instance;
    }
}
