<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocationResourceLoader_CachedService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Manuxi\SuluEventBundle\Content\ResourceLoader\LocationResourceLoader.cached' shared service.
     *
     * @return \Sulu\Content\Application\ResourceLoader\Loader\CachedResourceLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Manuxi\\SuluEventBundle\\Content\\ResourceLoader\\LocationResourceLoader.cached'] = new \Sulu\Content\Application\ResourceLoader\Loader\CachedResourceLoader(($container->privates['Manuxi\\SuluEventBundle\\Content\\ResourceLoader\\LocationResourceLoader.cached.inner'] ?? $container->load('getLocationResourceLoader_Cached_InnerService')));
    }
}
