<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocationControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Manuxi\SuluEventBundle\Controller\Admin\LocationController' shared service.
     *
     * @return \Manuxi\SuluEventBundle\Controller\Admin\LocationController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Manuxi\\SuluEventBundle\\Controller\\Admin\\LocationController'] = new \Manuxi\SuluEventBundle\Controller\Admin\LocationController(($container->services['Manuxi\\SuluEventBundle\\Repository\\LocationRepository'] ?? $container->load('getLocationRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['sulu_trash.trash_manager'] ?? $container->load('getSuluTrash_TrashManagerService')), ($container->services['sulu_core.list_builder.field_descriptor_factory'] ?? $container->load('getSuluCore_ListBuilder_FieldDescriptorFactoryService')), ($container->services['sulu_core.doctrine_list_builder_factory'] ?? $container->load('getSuluCore_DoctrineListBuilderFactoryService')), ($container->privates['sulu_core.rest_helper'] ?? $container->load('getSuluCore_RestHelperService')), ($container->services['sulu_media.media_manager'] ?? $container->load('getSuluMedia_MediaManagerService')), ($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)));
    }
}
