<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassiveBuild_Build_RegistryService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'massive_build.build.registry' shared service.
     *
     * @return \Massive\Bundle\BuildBundle\Build\BuildRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['massive_build.build.registry'] = $instance = new \Massive\Bundle\BuildBundle\Build\BuildRegistry();

        $instance->addBuilder(($container->privates['sulu_core.build.builder.database'] ??= new \Sulu\Bundle\CoreBundle\Build\DatabaseBuilder()));
        $instance->addBuilder(($container->privates['sulu_core.build.builder.fixtures'] ??= new \Sulu\Bundle\CoreBundle\Build\FixturesBuilder()));
        $instance->addBuilder(($container->privates['sulu_security.build.user'] ??= new \Sulu\Bundle\SecurityBundle\Build\UserBuilder()));
        $instance->addBuilder(($container->privates['sulu_security.build.security'] ??= new \Sulu\Bundle\SecurityBundle\Build\SecurityBuilder()));
        $instance->addBuilder(($container->privates['sulu_media.system_collections.builder'] ?? $container->load('getSuluMedia_SystemCollections_BuilderService')));
        $instance->addBuilder(($container->privates['sulu_page.homepage_builder'] ??= new \Sulu\Page\Infrastructure\Sulu\Build\HomepageBuilder()));
        $instance->addBuilder(($container->privates['massive_build.builder.virtual.prod'] ?? $container->load('getMassiveBuild_Builder_Virtual_ProdService')));
        $instance->addBuilder(($container->privates['massive_build.builder.virtual.dev'] ?? $container->load('getMassiveBuild_Builder_Virtual_DevService')));
        $instance->addBuilder(($container->privates['massive_build.builder.virtual.maintain'] ??= new \Massive\Bundle\BuildBundle\Builder\VirtualBuilder('maintain', ['node_order'])));

        return $instance;
    }
}
