<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPathCleanupInterfaceService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sulu\Route\Application\ResourceLocator\PathCleanup\PathCleanupInterface' shared service.
     *
     * @return \Sulu\Route\Application\ResourceLocator\PathCleanup\PathCleanup
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Sulu\\Route\\Application\\ResourceLocator\\PathCleanup\\PathCleanupInterface'] = new \Sulu\Route\Application\ResourceLocator\PathCleanup\PathCleanup(($container->privates['sulu_route.slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger()));
    }
}
