<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRouteRepositoryInterfaceService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sulu\Route\Domain\Repository\RouteRepositoryInterface' shared service.
     *
     * @return \Sulu\Route\Infrastructure\Doctrine\Repository\RouteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['Sulu\\Route\\Domain\\Repository\\RouteRepositoryInterface'])) {
            return $container->services['Sulu\\Route\\Domain\\Repository\\RouteRepositoryInterface'];
        }

        return $container->services['Sulu\\Route\\Domain\\Repository\\RouteRepositoryInterface'] = new \Sulu\Route\Infrastructure\Doctrine\Repository\RouteRepository($a);
    }
}
