<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRouteGeneratorInterfaceService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sulu\Route\Application\Routing\Generator\RouteGeneratorInterface' shared service.
     *
     * @return \Sulu\Route\Application\Routing\Generator\RouteGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Sulu\\Route\\Application\\Routing\\Generator\\RouteGeneratorInterface'] = new \Sulu\Route\Application\Routing\Generator\RouteGenerator(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            '.default' => ['privates', 'sulu_page.page_webspace_route_generator', 'getSuluPage_PageWebspaceRouteGeneratorService', true],
        ], [
            '.default' => 'Sulu\\Page\\Infrastructure\\Sulu\\Route\\PageWebspaceRouteGenerator',
        ]), ($container->privates['router.request_context'] ?? self::getRouter_RequestContextService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['translation.locale_switcher'] ?? $container->load('getTranslation_LocaleSwitcherService')));
    }
}
