<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_ContentNormalizerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_content.content_normalizer' shared service.
     *
     * @return \Sulu\Content\Application\ContentNormalizer\ContentNormalizer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_content.content_normalizer'] = new \Sulu\Content\Application\ContentNormalizer\ContentNormalizer(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['sulu_content.dimension_content_normalizer'] ??= new \Sulu\Content\Application\ContentNormalizer\Normalizer\DimensionContentNormalizer());
            yield 1 => ($container->privates['sulu_content.template_normalizer'] ??= new \Sulu\Content\Application\ContentNormalizer\Normalizer\TemplateNormalizer());
            yield 2 => ($container->privates['sulu_content.workflow_normalizer'] ??= new \Sulu\Content\Application\ContentNormalizer\Normalizer\WorkflowNormalizer());
            yield 3 => ($container->privates['sulu_content.taxonomy_normalizer'] ??= new \Sulu\Content\Application\ContentNormalizer\Normalizer\TaxonomyNormalizer());
            yield 4 => ($container->privates['sulu_content.excerpt_normalizer'] ??= new \Sulu\Content\Application\ContentNormalizer\Normalizer\ExcerptNormalizer());
            yield 5 => ($container->privates['sulu_content.seo_normalizer'] ??= new \Sulu\Content\Application\ContentNormalizer\Normalizer\SeoNormalizer());
            yield 6 => ($container->privates['sulu_content.routable_normalizer'] ??= new \Sulu\Content\Application\ContentNormalizer\Normalizer\RoutableNormalizer());
            yield 7 => ($container->privates['sulu_content.author_normalizer'] ??= new \Sulu\Content\Application\ContentNormalizer\Normalizer\AuthorNormalizer());
            yield 8 => ($container->privates['sulu_content.link_normalizer'] ??= new \Sulu\Content\Application\ContentNormalizer\Normalizer\LinkNormalizer());
            yield 9 => ($container->privates['sulu_content.shadow_normalizer'] ??= new \Sulu\Content\Application\ContentNormalizer\Normalizer\ShadowNormalizer());
            yield 10 => ($container->privates['sulu_content.auditable_normalizer'] ??= new \Sulu\Content\Application\ContentNormalizer\Normalizer\AuditableNormalizer());
            yield 11 => ($container->privates['sulu_content.secured_entity_normalizer'] ?? $container->load('getSuluContent_SecuredEntityNormalizerService'));
            yield 12 => ($container->privates['sulu_page.page_normalizer'] ??= new \Sulu\Page\Infrastructure\Sulu\Content\Normalizer\PageNormalizer());
            yield 13 => ($container->privates['sulu_page.page_excerpt_normalizer'] ??= new \Sulu\Page\Infrastructure\Sulu\Content\Normalizer\PageExcerptNormalizer());
            yield 14 => ($container->privates['sulu_event.event_normalizer'] ?? $container->load('getSuluEvent_EventNormalizerService'));
        }, 15));
    }
}
