<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCustomUrl_Routing_RouteCollectionLoaderService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_custom_url.routing.route_collection_loader' shared service.
     *
     * @return \Sulu\CustomUrl\Application\Routing\CustomUrlRouteCollectionLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_custom_url.routing.route_collection_loader'] = new \Sulu\CustomUrl\Application\Routing\CustomUrlRouteCollectionLoader(($container->services['Sulu\\CustomUrl\\Domain\\Repository\\CustomUrlRouteRepositoryInterface'] ?? $container->load('getCustomUrlRouteRepositoryInterfaceService')), ($container->privates['sulu_page.page_repository'] ?? self::getSuluPage_PageRepositoryService($container)), ($container->services['Sulu\\Route\\Domain\\Repository\\RouteRepositoryInterface'] ?? $container->load('getRouteRepositoryInterfaceService')), ($container->privates['sulu_content.content_aggregator'] ?? $container->load('getSuluContent_ContentAggregatorService')), ($container->privates['sulu_admin.metadata_provider_registry'] ?? $container->load('getSuluAdmin_MetadataProviderRegistryService')), ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->load('getSuluCore_Webspace_WebspaceManagerService')), 'test');
    }
}
