<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_TeaserManagerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.teaser_manager' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Teaser\TeaserManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_admin.teaser_provider_pool'] ?? $container->load('getSuluAdmin_TeaserProviderPoolService'));

        if (isset($container->privates['sulu_admin.teaser_manager'])) {
            return $container->privates['sulu_admin.teaser_manager'];
        }

        return $container->privates['sulu_admin.teaser_manager'] = new \Sulu\Bundle\AdminBundle\Teaser\TeaserManager($a);
    }
}
