<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_CacheControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_website.cache_controller' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\Controller\CacheController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_website.cache_controller'] = new \Sulu\Bundle\WebsiteBundle\Controller\CacheController(($container->services['sulu_website.http_cache.clearer'] ?? $container->load('getSuluWebsite_HttpCache_ClearerService')), ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->load('getSuluCore_Webspace_WebspaceManagerService')), ($container->services['sulu_security.security_checker'] ?? self::getSuluSecurity_SecurityCheckerService($container)));
    }
}
