<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_PropertyMetadataMapperRegistryService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.property_metadata_mapper_registry' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Metadata\SchemaMetadata\PropertyMetadataMapperRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_admin.property_metadata_mapper_registry'] = new \Sulu\Bundle\AdminBundle\Metadata\SchemaMetadata\PropertyMetadataMapperRegistry(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'text_line' => ['privates', 'sulu_admin.property_metadata_mapper.text', 'getSuluAdmin_PropertyMetadataMapper_TextService', true],
            'email' => ['privates', 'sulu_admin.property_metadata_mapper.email', 'getSuluAdmin_PropertyMetadataMapper_EmailService', true],
            'number' => ['privates', 'sulu_admin.property_metadata_mapper.number', 'getSuluAdmin_PropertyMetadataMapper_NumberService', true],
            'block' => ['privates', 'sulu_admin.property_metadata_mapper.block', 'getSuluAdmin_PropertyMetadataMapper_BlockService', true],
            'event_selection' => ['privates', 'sulu_admin.property_metadata_mapper.selection', 'getSuluAdmin_PropertyMetadataMapper_SelectionService', true],
            'single_event_selection' => ['privates', 'sulu_admin.property_metadata_mapper.single_selection', 'getSuluAdmin_PropertyMetadataMapper_SingleSelectionService', true],
            'teaser_selection' => ['privates', 'sulu_admin.property_metadata_mapper.teaser_selection', 'getSuluAdmin_PropertyMetadataMapper_TeaserSelectionService', true],
            'media_selection' => ['privates', 'sulu_media.type.media_selection_property_metadata_mapper', 'getSuluMedia_Type_MediaSelectionPropertyMetadataMapperService', true],
            'single_media_selection' => ['privates', 'sulu_media.type.single_media_selection_property_metadata_mapper', 'getSuluMedia_Type_SingleMediaSelectionPropertyMetadataMapperService', true],
            'image_map' => ['privates', 'sulu_media.type.image_map_property_metadata_mapper', 'getSuluMedia_Type_ImageMapPropertyMetadataMapperService', true],
            'page_tree_route' => ['privates', 'sulu_page.page_tree_route_property_metadata_mapper', 'getSuluPage_PageTreeRoutePropertyMetadataMapperService', true],
            'text_area' => ['privates', 'sulu_admin.property_metadata_mapper.text', 'getSuluAdmin_PropertyMetadataMapper_TextService', true],
            'page_selection' => ['privates', 'sulu_admin.property_metadata_mapper.selection', 'getSuluAdmin_PropertyMetadataMapper_SelectionService', true],
            'single_location_selection' => ['privates', 'sulu_admin.property_metadata_mapper.single_selection', 'getSuluAdmin_PropertyMetadataMapper_SingleSelectionService', true],
            'target_group_selection' => ['privates', 'sulu_admin.property_metadata_mapper.selection', 'getSuluAdmin_PropertyMetadataMapper_SelectionService', true],
            'single_page_selection' => ['privates', 'sulu_admin.property_metadata_mapper.single_selection', 'getSuluAdmin_PropertyMetadataMapper_SingleSelectionService', true],
            'category_selection' => ['privates', 'sulu_admin.property_metadata_mapper.selection', 'getSuluAdmin_PropertyMetadataMapper_SelectionService', true],
            'single_category_selection' => ['privates', 'sulu_admin.property_metadata_mapper.single_selection', 'getSuluAdmin_PropertyMetadataMapper_SingleSelectionService', true],
            'collection_selection' => ['privates', 'sulu_admin.property_metadata_mapper.selection', 'getSuluAdmin_PropertyMetadataMapper_SelectionService', true],
            'single_collection_selection' => ['privates', 'sulu_admin.property_metadata_mapper.single_selection', 'getSuluAdmin_PropertyMetadataMapper_SingleSelectionService', true],
            'tag_selection' => ['privates', 'sulu_admin.property_metadata_mapper.selection', 'getSuluAdmin_PropertyMetadataMapper_SelectionService', true],
            'single_account_selection' => ['privates', 'sulu_admin.property_metadata_mapper.single_selection', 'getSuluAdmin_PropertyMetadataMapper_SingleSelectionService', true],
            'contact_selection' => ['privates', 'sulu_admin.property_metadata_mapper.selection', 'getSuluAdmin_PropertyMetadataMapper_SelectionService', true],
            'single_contact_selection' => ['privates', 'sulu_admin.property_metadata_mapper.single_selection', 'getSuluAdmin_PropertyMetadataMapper_SingleSelectionService', true],
            'account_selection' => ['privates', 'sulu_admin.property_metadata_mapper.selection', 'getSuluAdmin_PropertyMetadataMapper_SelectionService', true],
            'single_contact_title_selection' => ['privates', 'sulu_admin.property_metadata_mapper.single_selection', 'getSuluAdmin_PropertyMetadataMapper_SingleSelectionService', true],
            'single_contact_position_selection' => ['privates', 'sulu_admin.property_metadata_mapper.single_selection', 'getSuluAdmin_PropertyMetadataMapper_SingleSelectionService', true],
        ], [
            'text_line' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\TextPropertyMetadataMapper',
            'email' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\EmailPropertyMetadataMapper',
            'number' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\NumberPropertyMetadataMapper',
            'block' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\BlockPropertyMetadataMapper',
            'event_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SelectionPropertyMetadataMapper',
            'single_event_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SingleSelectionPropertyMetadataMapper',
            'teaser_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\TeaserSelectionPropertyMetadataMapper',
            'media_selection' => 'Sulu\\Bundle\\MediaBundle\\Infrastructure\\Sulu\\Admin\\PropertyMetadataMapper\\MediaSelectionPropertyMetadataMapper',
            'single_media_selection' => 'Sulu\\Bundle\\MediaBundle\\Infrastructure\\Sulu\\Admin\\PropertyMetadataMapper\\SingleMediaSelectionPropertyMetadataMapper',
            'image_map' => 'Sulu\\Bundle\\MediaBundle\\Infrastructure\\Sulu\\Admin\\PropertyMetadataMapper\\ImageMapPropertyMetadataMapper',
            'page_tree_route' => 'Sulu\\Page\\Infrastructure\\Sulu\\Admin\\PropertyMetadataMapper\\PageTreeRoutePropertyMetadataMapper',
            'text_area' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\TextPropertyMetadataMapper',
            'page_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SelectionPropertyMetadataMapper',
            'single_location_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SingleSelectionPropertyMetadataMapper',
            'target_group_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SelectionPropertyMetadataMapper',
            'single_page_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SingleSelectionPropertyMetadataMapper',
            'category_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SelectionPropertyMetadataMapper',
            'single_category_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SingleSelectionPropertyMetadataMapper',
            'collection_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SelectionPropertyMetadataMapper',
            'single_collection_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SingleSelectionPropertyMetadataMapper',
            'tag_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SelectionPropertyMetadataMapper',
            'single_account_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SingleSelectionPropertyMetadataMapper',
            'contact_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SelectionPropertyMetadataMapper',
            'single_contact_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SingleSelectionPropertyMetadataMapper',
            'account_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SelectionPropertyMetadataMapper',
            'single_contact_title_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SingleSelectionPropertyMetadataMapper',
            'single_contact_position_selection' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\PropertyMetadataMapper\\SingleSelectionPropertyMetadataMapper',
        ]));
    }
}
