<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluEvent_EventUnlocalizedFieldsMergerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_event.event_unlocalized_fields_merger' shared service.
     *
     * @return \Manuxi\SuluEventBundle\Content\Merger\EventUnlocalizedFieldsMerger
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_event.event_unlocalized_fields_merger'] = new \Manuxi\SuluEventBundle\Content\Merger\EventUnlocalizedFieldsMerger();
    }
}
