<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_AdminMediaIndexListenerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_media.admin_media_index_listener' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Infrastructure\Sulu\Search\AdminMediaIndexListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['sulu_media.admin_media_index_listener'])) {
            return $container->privates['sulu_media.admin_media_index_listener'];
        }

        return $container->privates['sulu_media.admin_media_index_listener'] = new \Sulu\Bundle\MediaBundle\Infrastructure\Sulu\Search\AdminMediaIndexListener($a);
    }
}
