<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_PagePreviewProviderService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.page_preview_provider' shared service.
     *
     * @return \Sulu\Content\Infrastructure\Sulu\Preview\ContentObjectProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.page_preview_provider'] = new \Sulu\Content\Infrastructure\Sulu\Preview\ContentObjectProvider(($container->privates['sulu_admin.metadata_provider_registry'] ?? $container->load('getSuluAdmin_MetadataProviderRegistryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['sulu_content.content_aggregator'] ?? $container->load('getSuluContent_ContentAggregatorService')), ($container->privates['sulu_content.content_data_mapper'] ?? $container->load('getSuluContent_ContentDataMapperService')), 'Sulu\\Page\\Domain\\Model\\Page', NULL);
    }
}
