<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_FormOfAddressProviderService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_contact.form_of_address_provider' shared service.
     *
     * @return \Sulu\Bundle\ContactBundle\Provider\FormOfAddressProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_contact.form_of_address_provider'] = new \Sulu\Bundle\ContactBundle\Provider\FormOfAddressProvider(($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
