<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluTrash_TrashAdminService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_trash.trash_admin' shared service.
     *
     * @return \Sulu\Bundle\TrashBundle\Infrastructure\Sulu\Admin\TrashAdmin
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_trash.trash_admin'] = new \Sulu\Bundle\TrashBundle\Infrastructure\Sulu\Admin\TrashAdmin(($container->privates['sulu_admin.view_builder_factory'] ??= new \Sulu\Bundle\AdminBundle\Admin\View\ViewBuilderFactory()), ($container->services['sulu_security.security_checker'] ?? self::getSuluSecurity_SecurityCheckerService($container)), ($container->services['sulu.core.localization_manager'] ?? $container->load('getSulu_Core_LocalizationManagerService')), new RewindableGenerator(function () use ($container) {
            yield 'accounts' => ($container->privates['sulu_contact.account_trash_item_handler'] ?? $container->load('getSuluContact_AccountTrashItemHandlerService'));
            yield 'contacts' => ($container->privates['sulu_contact.contact_trash_item_handler'] ?? $container->load('getSuluContact_ContactTrashItemHandlerService'));
            yield 'analytics' => ($container->privates['sulu_website.analytics_trash_item_handler'] ?? $container->load('getSuluWebsite_AnalyticsTrashItemHandlerService'));
            yield 'tags' => ($container->privates['sulu_tag.tag_trash_item_handler'] ?? $container->load('getSuluTag_TagTrashItemHandlerService'));
            yield 'media' => ($container->privates['sulu_media.media_trash_item_handler'] ?? $container->load('getSuluMedia_MediaTrashItemHandlerService'));
            yield 'collections' => ($container->privates['sulu_media.collection_trash_item_handler'] ?? $container->load('getSuluMedia_CollectionTrashItemHandlerService'));
            yield 'categories' => ($container->privates['sulu_category.category_trash_item_handler'] ?? $container->load('getSuluCategory_CategoryTrashItemHandlerService'));
            yield 'custom_urls' => ($container->privates['sulu_custom_urls.custom_url_trash_item_handler'] ?? $container->load('getSuluCustomUrls_CustomUrlTrashItemHandlerService'));
            yield 'pages' => ($container->privates['sulu_page.trash_item_handler'] ?? $container->load('getSuluPage_TrashItemHandlerService'));
            yield 'events' => ($container->privates['sulu_event.trash_item_handler'] ?? $container->load('getSuluEvent_TrashItemHandlerService'));
            yield 'locations' => ($container->privates['Manuxi\\SuluEventBundle\\Trash\\LocationTrashItemHandler'] ?? $container->load('getLocationTrashItemHandlerService'));
        }, 11));
    }
}
