<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_PageTeaserProviderService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.page_teaser_provider' shared service.
     *
     * @return \Sulu\Page\Infrastructure\Sulu\Content\PageTeaserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sulu_page.page_teaser_provider'])) {
            return $container->privates['sulu_page.page_teaser_provider'];
        }

        return $container->privates['sulu_page.page_teaser_provider'] = new \Sulu\Page\Infrastructure\Sulu\Content\PageTeaserProvider(($container->privates['sulu_content.content_manager'] ?? $container->load('getSuluContent_ContentManagerService')), $a, ($container->privates['sulu_content.content_metadata_inspector'] ?? $container->load('getSuluContent_ContentMetadataInspectorService')), ($container->privates['sulu_admin.metadata_provider_registry'] ?? $container->load('getSuluAdmin_MetadataProviderRegistryService')), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->privates['sulu_content.content_enhancer'] ?? $container->load('getSuluContent_ContentEnhancerService')));
    }
}
