<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_TwigService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_contact.twig' shared service.
     *
     * @return \Sulu\Bundle\ContactBundle\Twig\ContactTwigExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_contact.twig'] = new \Sulu\Bundle\ContactBundle\Twig\ContactTwigExtension(($container->privates['sulu_contact.twig.cache_adapter'] ??= new \Symfony\Component\Cache\Adapter\ArrayAdapter()), ($container->services['sulu.repository.contact'] ?? $container->load('getSulu_Repository_ContactService')));
    }
}
