<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_ContentViewBuilderFactoryService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_content.content_view_builder_factory' shared service.
     *
     * @return \Sulu\Content\Infrastructure\Sulu\Admin\ContentViewBuilderFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_content.content_view_builder_factory'] = new \Sulu\Content\Infrastructure\Sulu\Admin\ContentViewBuilderFactory(($container->privates['sulu_admin.view_builder_factory'] ??= new \Sulu\Bundle\AdminBundle\Admin\View\ViewBuilderFactory()), ($container->privates['sulu_preview.preview_object_provider_registry'] ?? $container->load('getSuluPreview_PreviewObjectProviderRegistryService')), ($container->privates['sulu_content.content_metadata_inspector'] ?? $container->load('getSuluContent_ContentMetadataInspectorService')), ($container->services['sulu_security.security_checker'] ?? self::getSuluSecurity_SecurityCheckerService($container)), $container->parameters['sulu_content.content_settings_forms'], $container->parameters['sulu_content.content_excerpt_forms'], $container->parameters['sulu_content.content_seo_forms']);
    }
}
