<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSession_Storage_Factory_MockFileService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'session.storage.factory.mock_file' shared service.
     *
     * @return \Symfony\Component\HttpFoundation\Session\Storage\MockFileSessionStorageFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['session.storage.factory.mock_file'] = new \Symfony\Component\HttpFoundation\Session\Storage\MockFileSessionStorageFactory(($container->targetDir.''.'/sessions'), 'MOCKSESSID', new \Symfony\Component\HttpFoundation\Session\Storage\MetadataBag('_sf2_meta', 0));
    }
}
