<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluActivity_ActivityRepository_DoctrineService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_activity.activity_repository.doctrine' shared service.
     *
     * @return \Sulu\Bundle\ActivityBundle\Infrastructure\Doctrine\Repository\ActivityRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sulu_activity.activity_repository.doctrine'])) {
            return $container->privates['sulu_activity.activity_repository.doctrine'];
        }

        return $container->privates['sulu_activity.activity_repository.doctrine'] = new \Sulu\Bundle\ActivityBundle\Infrastructure\Doctrine\Repository\ActivityRepository($a, false);
    }
}
