<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_ContactMediaControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_contact.contact_media_controller' shared service.
     *
     * @return \Sulu\Bundle\ContactBundle\Controller\ContactMediaController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_contact.contact_media_controller'] = new \Sulu\Bundle\ContactBundle\Controller\ContactMediaController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->services['sulu_core.doctrine_rest_helper'] ?? $container->load('getSuluCore_DoctrineRestHelperService')), ($container->services['sulu_core.doctrine_list_builder_factory'] ?? $container->load('getSuluCore_DoctrineListBuilderFactoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['sulu.repository.media'] ?? $container->load('getSulu_Repository_MediaService')), ($container->services['sulu_media.media_manager'] ?? $container->load('getSuluMedia_MediaManagerService')), ($container->services['sulu_contact.contact_manager'] ?? $container->load('getSuluContact_ContactManagerService')), ($container->privates['sulu_activity.domain_event_collector'] ?? $container->load('getSuluActivity_DomainEventCollectorService')), 'Sulu\\Bundle\\ContactBundle\\Entity\\Contact', 'Sulu\\Bundle\\MediaBundle\\Entity\\Media', ($container->privates['sulu_media.media_list_builder_factory'] ?? $container->load('getSuluMedia_MediaListBuilderFactoryService')), ($container->privates['sulu_media.media_list_representation_factory'] ?? $container->load('getSuluMedia_MediaListRepresentationFactoryService')), ($container->services['sulu_core.list_builder.field_descriptor_factory'] ?? $container->load('getSuluCore_ListBuilder_FieldDescriptorFactoryService')));
    }
}
