<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_Build_SecurityService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_security.build.security' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\Build\SecurityBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_security.build.security'] = new \Sulu\Bundle\SecurityBundle\Build\SecurityBuilder();
    }
}
