<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSearch_SearchAdminService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_search.search_admin' shared service.
     *
     * @return \Sulu\Search\Infrastructure\Sulu\Admin\SearchAdmin
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_search.search_admin'] = new \Sulu\Search\Infrastructure\Sulu\Admin\SearchAdmin(($container->privates['sulu_admin.view_builder_factory'] ??= new \Sulu\Bundle\AdminBundle\Admin\View\ViewBuilderFactory()));
    }
}
