<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_PageSmartContentProviderService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.page_smart_content_provider' shared service.
     *
     * @return \Sulu\Page\Infrastructure\Sulu\Content\PageSmartContentProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sulu_page.page_smart_content_provider'])) {
            return $container->privates['sulu_page.page_smart_content_provider'];
        }
        $b = ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container));

        if (isset($container->privates['sulu_page.page_smart_content_provider'])) {
            return $container->privates['sulu_page.page_smart_content_provider'];
        }

        return $container->privates['sulu_page.page_smart_content_provider'] = new \Sulu\Page\Infrastructure\Sulu\Content\PageSmartContentProvider(($container->privates['sulu_content.dimension_content_query_enhancer'] ??= new \Sulu\Content\Infrastructure\Doctrine\DimensionContentQueryEnhancer()), ($container->privates['sulu_admin.form_metadata_provider'] ?? $container->load('getSuluAdmin_FormMetadataProviderService')), ($container->privates['sulu_admin.smart_content_query_enhancer'] ??= new \Sulu\Bundle\AdminBundle\SmartContent\SmartContentQueryEnhancer()), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), $a, $container->parameters['kernel.bundles'], ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->load('getSuluCore_Webspace_WebspaceManagerService')), ($container->privates['sulu_security.access_control_query_enhancer'] ?? self::getSuluSecurity_AccessControlQueryEnhancerService($container)), $b, $container->parameters['sulu_security.permissions']);
    }
}
