<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_UnpublishTransitionSubscriberService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_content.unpublish_transition_subscriber' shared service.
     *
     * @return \Sulu\Content\Application\ContentWorkflow\Subscriber\UnpublishTransitionSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sulu_content.unpublish_transition_subscriber'])) {
            return $container->privates['sulu_content.unpublish_transition_subscriber'];
        }

        return $container->privates['sulu_content.unpublish_transition_subscriber'] = new \Sulu\Content\Application\ContentWorkflow\Subscriber\UnpublishTransitionSubscriber(($container->privates['sulu_content.dimension_content_repository'] ?? $container->load('getSuluContent_DimensionContentRepositoryService')), $a);
    }
}
