<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_ResourceLoaderProviderService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_content.resource_loader_provider' shared service.
     *
     * @return \Sulu\Content\Application\ResourceLoader\ResourceLoaderProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_content.resource_loader_provider'] = new \Sulu\Content\Application\ResourceLoader\ResourceLoaderProvider(new RewindableGenerator(function () use ($container) {
            yield 'contact' => ($container->privates['sulu_contact.contact_resource_loader.cached'] ?? $container->load('getSuluContact_ContactResourceLoader_CachedService'));
            yield 'account' => ($container->privates['sulu_contact.account_resource_loader.cached'] ?? $container->load('getSuluContact_AccountResourceLoader_CachedService'));
            yield 'tag' => ($container->privates['sulu_tag.tag_resource_loader.cached'] ?? $container->load('getSuluTag_TagResourceLoader_CachedService'));
            yield 'media' => ($container->privates['sulu_media.media_resource_loader.cached'] ?? $container->load('getSuluMedia_MediaResourceLoader_CachedService'));
            yield 'collection' => ($container->privates['sulu_media.collection_resource_loader.cached'] ?? $container->load('getSuluMedia_CollectionResourceLoader_CachedService'));
            yield 'category' => ($container->privates['sulu_category.category_resource_loader.cached'] ?? $container->load('getSuluCategory_CategoryResourceLoader_CachedService'));
            yield 'link' => ($container->privates['sulu_content.link_resource_loader.cached'] ?? $container->load('getSuluContent_LinkResourceLoader_CachedService'));
            yield 'teaser' => ($container->privates['sulu_content.teaser_resource_loader.cached'] ?? $container->load('getSuluContent_TeaserResourceLoader_CachedService'));
            yield 'page' => ($container->privates['sulu_page.page_resource_loader.cached'] ?? $container->load('getSuluPage_PageResourceLoader_CachedService'));
            yield 'events' => ($container->privates['sulu_event.resource_loader.event.cached'] ?? $container->load('getSuluEvent_ResourceLoader_Event_CachedService'));
            yield 'locations' => ($container->privates['Manuxi\\SuluEventBundle\\Content\\ResourceLoader\\LocationResourceLoader.cached'] ?? $container->load('getLocationResourceLoader_CachedService'));
        }, 11));
    }
}
