<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_PropertiesXmlParserService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.properties_xml_parser' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\Parser\PropertiesXmlParser
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_admin.properties_xml_parser'] = new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\Parser\PropertiesXmlParser(($container->privates['sulu_admin.tag_xml_parser'] ??= new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\Parser\TagXmlParser()), ($container->privates['sulu_admin.meta_xml_parser'] ?? $container->load('getSuluAdmin_MetaXmlParserService')));
    }
}
