<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_AccountResourceLoader_Cached_InnerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_contact.account_resource_loader.cached.inner' shared service.
     *
     * @return \Sulu\Bundle\ContactBundle\Infrastructure\Sulu\Content\ResourceLoader\AccountResourceLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_contact.account_manager'] ?? $container->load('getSuluContact_AccountManagerService'));

        if (isset($container->privates['sulu_contact.account_resource_loader.cached.inner'])) {
            return $container->privates['sulu_contact.account_resource_loader.cached.inner'];
        }

        return $container->privates['sulu_contact.account_resource_loader.cached.inner'] = new \Sulu\Bundle\ContactBundle\Infrastructure\Sulu\Content\ResourceLoader\AccountResourceLoader($a);
    }
}
