<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluEvent_Search_AdminProviderService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_event.search.admin_provider' shared service.
     *
     * @return \Manuxi\SuluEventBundle\Search\EventAdminSearchProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_event.search.admin_provider'] = new \Manuxi\SuluEventBundle\Search\EventAdminSearchProvider(($container->services['Manuxi\\SuluEventBundle\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')), ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->load('getSuluCore_Webspace_WebspaceManagerService')), ($container->privates['sulu_content.content_aggregator'] ?? $container->load('getSuluContent_ContentAggregatorService')));
    }
}
