<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_Serializer_MediaPermissionsService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_security.serializer.media_permissions' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Serializer\Subscriber\MediaPermissionsSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_security.access_control_manager'] ?? $container->load('getSuluSecurity_AccessControlManagerService'));

        if (isset($container->privates['sulu_security.serializer.media_permissions'])) {
            return $container->privates['sulu_security.serializer.media_permissions'];
        }

        return $container->privates['sulu_security.serializer.media_permissions'] = new \Sulu\Bundle\MediaBundle\Serializer\Subscriber\MediaPermissionsSubscriber($a, ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)));
    }
}
