<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluRoute_ResourceLocatorGenerateControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_route.resource_locator_generate_controller' shared service.
     *
     * @return \Sulu\Route\Userinterface\Controller\Admin\ResourceLocatorGenerateController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_route.resource_locator_generate_controller'] = new \Sulu\Route\Userinterface\Controller\Admin\ResourceLocatorGenerateController(($container->privates['sulu_route.resource_locator_generator'] ?? $container->load('getSuluRoute_ResourceLocatorGeneratorService')));
    }
}
