<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAudienceTargeting_AudienceTargetingSmartContentFiltersVisitorService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_audience_targeting.audience_targeting_smart_content_filters_visitor' shared service.
     *
     * @return \Sulu\Bundle\AudienceTargetingBundle\Visitor\AudienceTargetingSmartContentFiltersVisitor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_audience_targeting.audience_targeting_smart_content_filters_visitor'] = new \Sulu\Bundle\AudienceTargetingBundle\Visitor\AudienceTargetingSmartContentFiltersVisitor(($container->services['sulu_audience_targeting.target_group_store'] ??= new \Sulu\Bundle\AudienceTargetingBundle\TargetGroup\TargetGroupStore()));
    }
}
