<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_ShadowMergerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_content.shadow_merger' shared service.
     *
     * @return \Sulu\Content\Application\ContentMerger\Merger\ShadowMerger
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_content.shadow_merger'] = new \Sulu\Content\Application\ContentMerger\Merger\ShadowMerger();
    }
}
