<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_AdminPageIndexListenerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.admin_page_index_listener' shared service.
     *
     * @return \Sulu\Page\Infrastructure\Sulu\Search\AdminPageIndexListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['sulu_page.admin_page_index_listener'])) {
            return $container->privates['sulu_page.admin_page_index_listener'];
        }

        return $container->privates['sulu_page.admin_page_index_listener'] = new \Sulu\Page\Infrastructure\Sulu\Search\AdminPageIndexListener($a);
    }
}
