<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPreview_PreviewControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_preview.preview_controller' shared service.
     *
     * @return \Sulu\Bundle\PreviewBundle\UserInterface\Controller\PreviewController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_preview.preview_controller'] = new \Sulu\Bundle\PreviewBundle\UserInterface\Controller\PreviewController(($container->privates['sulu_preview.preview'] ?? $container->load('getSuluPreview_PreviewService')), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), NULL);
    }
}
