<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_PasswordPatternFormMetadataVisitorService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_security.password_pattern_form_metadata_visitor' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\Metadata\PasswordPolicyFormMetadataVisitor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_security.password_pattern_form_metadata_visitor'] = new \Sulu\Bundle\SecurityBundle\Metadata\PasswordPolicyFormMetadataVisitor(($container->services['translator'] ?? self::getTranslatorService($container)), NULL, NULL);
    }
}
