<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluReference_ReferenceListViewBuilderFactoryService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_reference.reference_list_view_builder_factory' shared service.
     *
     * @return \Sulu\Bundle\ReferenceBundle\Infrastructure\Sulu\Admin\View\ReferenceViewBuilderFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_reference.reference_list_view_builder_factory'] = new \Sulu\Bundle\ReferenceBundle\Infrastructure\Sulu\Admin\View\ReferenceViewBuilderFactory(($container->privates['sulu_admin.view_builder_factory'] ??= new \Sulu\Bundle\AdminBundle\Admin\View\ViewBuilderFactory()), ($container->services['sulu_security.security_checker'] ?? self::getSuluSecurity_SecurityCheckerService($container)));
    }
}
