<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_DoctrineRouteCleanupListenerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_content.doctrine_route_cleanup_listener' shared service.
     *
     * @return \Sulu\Content\Infrastructure\Doctrine\EventListener\RouteCleanupListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_content.doctrine_route_cleanup_listener'] = new \Sulu\Content\Infrastructure\Doctrine\EventListener\RouteCleanupListener();
    }
}
