<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_Image_TransformationPoolService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_media.image.transformation_pool' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Media\ImageConverter\TransformationPool
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_media.image.transformation_pool'] = new \Sulu\Bundle\MediaBundle\Media\ImageConverter\TransformationPool(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'crop' => ['privates', 'sulu_media.image.transformation.crop', 'getSuluMedia_Image_Transformation_CropService', true],
            'paste' => ['privates', 'sulu_media.image.transformation.paste', 'getSuluMedia_Image_Transformation_PasteService', true],
            'blur' => ['privates', 'sulu_media.image.transformation.blur', 'getSuluMedia_Image_Transformation_BlurService', true],
            'gamma' => ['privates', 'sulu_media.image.transformation.gamma', 'getSuluMedia_Image_Transformation_GammaService', true],
            'grayscale' => ['privates', 'sulu_media.image.transformation.grayscale', 'getSuluMedia_Image_Transformation_GrayscaleService', true],
            'negative' => ['privates', 'sulu_media.image.transformation.negative', 'getSuluMedia_Image_Transformation_NegativeService', true],
            'sharpen' => ['privates', 'sulu_media.image.transformation.sharpen', 'getSuluMedia_Image_Transformation_SharpenService', true],
        ], [
            'crop' => 'Sulu\\Bundle\\MediaBundle\\Media\\ImageConverter\\Transformation\\CropTransformation',
            'paste' => 'Sulu\\Bundle\\MediaBundle\\Media\\ImageConverter\\Transformation\\PasteTransformation',
            'blur' => 'Sulu\\Bundle\\MediaBundle\\Media\\ImageConverter\\Transformation\\BlurTransformation',
            'gamma' => 'Sulu\\Bundle\\MediaBundle\\Media\\ImageConverter\\Transformation\\GammaTransformation',
            'grayscale' => 'Sulu\\Bundle\\MediaBundle\\Media\\ImageConverter\\Transformation\\GrayscaleTransformation',
            'negative' => 'Sulu\\Bundle\\MediaBundle\\Media\\ImageConverter\\Transformation\\NegativeTransformation',
            'sharpen' => 'Sulu\\Bundle\\MediaBundle\\Media\\ImageConverter\\Transformation\\SharpenTransformation',
        ]));
    }
}
