<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluTrash_TrashManagerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_trash.trash_manager' shared service.
     *
     * @return \Sulu\Bundle\TrashBundle\Application\TrashManager\TrashManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_trash.trash_item_repository'] ?? $container->load('getSuluTrash_TrashItemRepositoryService'));

        if (isset($container->privates['sulu_trash.trash_manager'])) {
            return $container->privates['sulu_trash.trash_manager'];
        }
        $b = ($container->privates['sulu_activity.domain_event_collector'] ?? $container->load('getSuluActivity_DomainEventCollectorService'));

        if (isset($container->privates['sulu_trash.trash_manager'])) {
            return $container->privates['sulu_trash.trash_manager'];
        }
        $c = ($container->privates['.service_locator.Dm1CUYF'] ?? $container->load('get_ServiceLocator_Dm1CUYFService'));

        if (isset($container->privates['sulu_trash.trash_manager'])) {
            return $container->privates['sulu_trash.trash_manager'];
        }

        return $container->privates['sulu_trash.trash_manager'] = new \Sulu\Bundle\TrashBundle\Application\TrashManager\TrashManager($a, $b, $c, $c, new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'media' => ['privates', 'sulu_media.media_trash_item_handler', 'getSuluMedia_MediaTrashItemHandlerService', true],
        ], [
            'media' => 'Sulu\\Bundle\\MediaBundle\\Trash\\MediaTrashItemHandler',
        ]));
    }
}
