<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluEvent_TwigExtensionService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_event.twig_extension' shared service.
     *
     * @return \Manuxi\SuluEventBundle\Twig\EventTwigExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sulu_event.twig_extension'])) {
            return $container->privates['sulu_event.twig_extension'];
        }

        return $container->privates['sulu_event.twig_extension'] = new \Manuxi\SuluEventBundle\Twig\EventTwigExtension($a, ($container->privates['sulu_content.content_aggregator'] ?? $container->load('getSuluContent_ContentAggregatorService')), ($container->services['sulu_content.content_resolver'] ?? $container->load('getSuluContent_ContentResolverService')), ($container->services['sulu_core.webspace.request_analyzer'] ?? self::getSuluCore_Webspace_RequestAnalyzerService($container)));
    }
}
