<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_AdminService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_media.admin' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Admin\MediaAdmin
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_media.admin'] = new \Sulu\Bundle\MediaBundle\Admin\MediaAdmin(($container->privates['sulu_admin.view_builder_factory'] ??= new \Sulu\Bundle\AdminBundle\Admin\View\ViewBuilderFactory()), ($container->services['sulu_security.security_checker'] ?? self::getSuluSecurity_SecurityCheckerService($container)), ($container->services['sulu.core.localization_manager'] ?? $container->load('getSulu_Core_LocalizationManagerService')), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->load('getSuluCore_Webspace_WebspaceManagerService')), ($container->privates['sulu_activity.activity_list_view_builder_factory'] ?? $container->load('getSuluActivity_ActivityListViewBuilderFactoryService')), ($container->privates['sulu_reference.reference_list_view_builder_factory'] ?? $container->load('getSuluReference_ReferenceListViewBuilderFactoryService')));
    }
}
