<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_SmartContentQueryEnhancerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.smart_content_query_enhancer' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\SmartContent\SmartContentQueryEnhancer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_admin.smart_content_query_enhancer'] = new \Sulu\Bundle\AdminBundle\SmartContent\SmartContentQueryEnhancer();
    }
}
