<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_NumberFilterTypeService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_core.number_filter_type' shared service.
     *
     * @return \Sulu\Component\Rest\ListBuilder\Filter\NumberFilterType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.number_filter_type'] = new \Sulu\Component\Rest\ListBuilder\Filter\NumberFilterType();
    }
}
