<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_RoleSettingControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_security.role_setting_controller' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\Controller\RoleSettingController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_security.role_setting_controller'] = new \Sulu\Bundle\SecurityBundle\Controller\RoleSettingController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sulu.repository.role_setting'] ?? $container->load('getSulu_Repository_RoleSettingService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
