<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluReference_ReferenceControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_reference.reference_controller' shared service.
     *
     * @return \Sulu\Bundle\ReferenceBundle\UserInterface\Controller\Admin\ReferenceController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_reference.reference_controller'] = new \Sulu\Bundle\ReferenceBundle\UserInterface\Controller\Admin\ReferenceController(($container->privates['sulu_reference.reference_repository'] ?? $container->load('getSuluReference_ReferenceRepositoryService')), ($container->services['sulu_security.security_checker'] ?? self::getSuluSecurity_SecurityCheckerService($container)), ($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)));
    }
}
