<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_SaltGeneratorService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_security.salt_generator' shared service.
     *
     * @return \Sulu\Component\Security\Authentication\SaltGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_security.salt_generator'] = new \Sulu\Component\Security\Authentication\SaltGenerator();
    }
}
