<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_AdminService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_security.admin' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\Admin\SecurityAdmin
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['sulu_security.admin'] = $container->createProxy('SecurityAdminGhostDb0cac3', static fn () => \SecurityAdminGhostDb0cac3::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        return ($lazyLoad->__construct(($container->privates['sulu_admin.view_builder_factory'] ??= new \Sulu\Bundle\AdminBundle\Admin\View\ViewBuilderFactory()), ($container->services['sulu_security.security_checker'] ?? self::getSuluSecurity_SecurityCheckerService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['sulu_admin.admin_pool'] ?? $container->load('getSuluAdmin_AdminPoolService')), $container->parameters['sulu_admin.resources']) && false ?: $lazyLoad);
    }
}
