<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_ContentResolverService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_content.content_resolver' shared service.
     *
     * @return \Sulu\Content\Application\ContentResolver\ContentResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_content.resolvable_resource_loader'] ?? $container->load('getSuluContent_ResolvableResourceLoaderService'));

        if (isset($container->services['sulu_content.content_resolver'])) {
            return $container->services['sulu_content.content_resolver'];
        }

        return $container->services['sulu_content.content_resolver'] = new \Sulu\Content\Application\ContentResolver\ContentResolver(($container->privates['sulu_content.content_view_resolver'] ?? $container->load('getSuluContent_ContentViewResolverService')), $a, ($container->privates['sulu_content.resolvable_resource_queue_processor'] ??= new \Sulu\Content\Application\ContentResolver\ResolvableResourceQueue\ResolvableResourceQueueProcessor()), ($container->privates['sulu_content.resolvable_resource_replacer'] ?? $container->load('getSuluContent_ResolvableResourceReplacerService')), ($container->privates['sulu_content.content_view_data_normalizer'] ?? $container->load('getSuluContent_ContentViewDataNormalizerService')), ($container->privates['sulu_content.content_aggregator'] ?? $container->load('getSuluContent_ContentAggregatorService')), 5, ($container->privates['sulu_content.content_enhancer'] ?? $container->load('getSuluContent_ContentEnhancerService')));
    }
}
