<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Repository_TargetGroupWebspaceService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu.repository.target_group_webspace' shared service.
     *
     * @return \Sulu\Bundle\AudienceTargetingBundle\Entity\TargetGroupWebspaceRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['sulu.repository.target_group_webspace'] = $container->createProxy('TargetGroupWebspaceRepositoryGhostB3d1ee8', static fn () => \TargetGroupWebspaceRepositoryGhostB3d1ee8::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        return ($lazyLoad->__construct($a, $a->getClassMetadata('Sulu\\Bundle\\AudienceTargetingBundle\\Entity\\TargetGroupWebspace')) && false ?: $lazyLoad);
    }
}
