<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_MetadataProviderRegistryService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.metadata_provider_registry' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Metadata\MetadataProviderRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_admin.metadata_provider_registry'] = new \Sulu\Bundle\AdminBundle\Metadata\MetadataProviderRegistry(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'form' => ['privates', 'sulu_admin.form_metadata_provider', 'getSuluAdmin_FormMetadataProviderService', true],
            'list' => ['privates', 'sulu_admin.list_metadata_provider', 'getSuluAdmin_ListMetadataProviderService', true],
        ], [
            'form' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\FormMetadata\\FormMetadataProvider',
            'list' => 'Sulu\\Bundle\\AdminBundle\\Metadata\\ListMetadata\\ListMetadataProvider',
        ]));
    }
}
