<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_DoctrineListBuilderFactoryService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_core.doctrine_list_builder_factory' shared service.
     *
     * @return \Sulu\Component\Rest\ListBuilder\Doctrine\DoctrineListBuilderFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_core.doctrine_list_builder_factory'] = new \Sulu\Component\Rest\ListBuilder\Doctrine\DoctrineListBuilderFactory(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['sulu_core.list_builder_filter_type_registry'] ?? $container->load('getSuluCore_ListBuilderFilterTypeRegistryService')), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), $container->parameters['sulu_security.permissions'], ($container->privates['sulu_security.access_control_query_enhancer'] ?? self::getSuluSecurity_AccessControlQueryEnhancerService($container)));
    }
}
