<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_NavigationRepositoryService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.navigation_repository' shared service.
     *
     * @return \Sulu\Page\Infrastructure\Doctrine\Repository\NavigationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sulu_page.navigation_repository'])) {
            return $container->privates['sulu_page.navigation_repository'];
        }
        $b = ($container->services['sulu_content.content_resolver'] ?? $container->load('getSuluContent_ContentResolverService'));

        if (isset($container->privates['sulu_page.navigation_repository'])) {
            return $container->privates['sulu_page.navigation_repository'];
        }

        return $container->privates['sulu_page.navigation_repository'] = new \Sulu\Page\Infrastructure\Doctrine\Repository\NavigationRepository($a, ($container->privates['sulu_content.dimension_content_query_enhancer'] ??= new \Sulu\Content\Infrastructure\Doctrine\DimensionContentQueryEnhancer()), ($container->privates['sulu_content.content_aggregator'] ?? $container->load('getSuluContent_ContentAggregatorService')), $b);
    }
}
