<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_PageLinkDimensionContentEnhancerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.page_link_dimension_content_enhancer' shared service.
     *
     * @return \Sulu\Page\Infrastructure\Sulu\Content\ContentResolver\PageLinkDimensionContentEnhancer
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_markup.link_tag.provider_pool'] ?? $container->load('getSuluMarkup_LinkTag_ProviderPoolService'));

        if (isset($container->privates['sulu_page.page_link_dimension_content_enhancer'])) {
            return $container->privates['sulu_page.page_link_dimension_content_enhancer'];
        }

        return $container->privates['sulu_page.page_link_dimension_content_enhancer'] = new \Sulu\Page\Infrastructure\Sulu\Content\ContentResolver\PageLinkDimensionContentEnhancer(($container->privates['sulu_page.page_repository'] ?? self::getSuluPage_PageRepositoryService($container)), ($container->privates['sulu_content.content_aggregator'] ?? $container->load('getSuluContent_ContentAggregatorService')), $a);
    }
}
