<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_ReferenceDoctrineEventListenerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_content.reference_doctrine_event_listener' shared service.
     *
     * @return \Sulu\Content\Infrastructure\Sulu\Reference\ReferenceDoctrineEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['sulu_content.reference_doctrine_event_listener'])) {
            return $container->privates['sulu_content.reference_doctrine_event_listener'];
        }

        return $container->privates['sulu_content.reference_doctrine_event_listener'] = new \Sulu\Content\Infrastructure\Sulu\Reference\ReferenceDoctrineEventListener($a, ($container->privates['sulu_reference.reference_repository'] ?? $container->load('getSuluReference_ReferenceRepositoryService')));
    }
}
