<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_Type_ImageMapPropertyMetadataMapperService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_media.type.image_map_property_metadata_mapper' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Infrastructure\Sulu\Admin\PropertyMetadataMapper\ImageMapPropertyMetadataMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_admin.schema_metadata_provider'] ?? $container->load('getSuluAdmin_SchemaMetadataProviderService'));

        if (isset($container->privates['sulu_media.type.image_map_property_metadata_mapper'])) {
            return $container->privates['sulu_media.type.image_map_property_metadata_mapper'];
        }

        return $container->privates['sulu_media.type.image_map_property_metadata_mapper'] = new \Sulu\Bundle\MediaBundle\Infrastructure\Sulu\Admin\PropertyMetadataMapper\ImageMapPropertyMetadataMapper($a);
    }
}
