<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluEvent_ResourceLoader_Event_Cached_InnerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_event.resource_loader.event.cached.inner' shared service.
     *
     * @return \Manuxi\SuluEventBundle\Content\ResourceLoader\EventResourceLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_event.resource_loader.event.cached.inner'] = new \Manuxi\SuluEventBundle\Content\ResourceLoader\EventResourceLoader(($container->services['Manuxi\\SuluEventBundle\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')));
    }
}
