<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_Analytics_ManagerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_website.analytics.manager' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\Analytics\AnalyticsManager
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_website.analytics.manager'] = new \Sulu\Bundle\WebsiteBundle\Analytics\AnalyticsManager(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['sulu.repository.analytics'] ?? $container->load('getSulu_Repository_AnalyticsService')), ($container->privates['sulu_website.domains.repository'] ?? $container->load('getSuluWebsite_Domains_RepositoryService')), 'test', ($container->privates['sulu_activity.domain_event_collector'] ?? $container->load('getSuluActivity_DomainEventCollectorService')), ($container->privates['sulu_trash.trash_manager'] ?? $container->load('getSuluTrash_TrashManagerService')));
    }
}
