<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_AccountResourceLoader_CachedService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_contact.account_resource_loader.cached' shared service.
     *
     * @return \Sulu\Content\Application\ResourceLoader\Loader\CachedResourceLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_contact.account_resource_loader.cached.inner'] ?? $container->load('getSuluContact_AccountResourceLoader_Cached_InnerService'));

        if (isset($container->privates['sulu_contact.account_resource_loader.cached'])) {
            return $container->privates['sulu_contact.account_resource_loader.cached'];
        }

        return $container->privates['sulu_contact.account_resource_loader.cached'] = new \Sulu\Content\Application\ResourceLoader\Loader\CachedResourceLoader($a);
    }
}
