<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_MediaStreamControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_media.media_stream_controller' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Controller\MediaStreamController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_media.media_stream_controller'] = new \Sulu\Bundle\MediaBundle\Controller\MediaStreamController(($container->services['sulu_media.disposition_type.resolver'] ??= new \Sulu\Bundle\MediaBundle\Media\DispositionType\DispositionTypeResolver('attachment', [], [])), ($container->services['sulu.repository.media'] ?? $container->load('getSulu_Repository_MediaService')), ($container->services['Sulu\\Route\\Application\\ResourceLocator\\PathCleanup\\PathCleanupInterface'] ?? $container->load('getPathCleanupInterfaceService')), ($container->services['sulu_media.format_manager'] ?? $container->load('getSuluMedia_FormatManagerService')), ($container->services['sulu_media.format_cache'] ?? $container->load('getSuluMedia_FormatCacheService')), ($container->services['sulu_media.media_manager'] ?? $container->load('getSuluMedia_MediaManagerService')), ($container->services['sulu_media.storage'] ?? $container->load('getSuluMedia_StorageService')), ($container->services['sulu_security.security_checker'] ?? self::getSuluSecurity_SecurityCheckerService($container)));
    }
}
