<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluEvent_PropertyResolver_EventSelectionService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_event.property_resolver.event_selection' shared service.
     *
     * @return \Manuxi\SuluEventBundle\Content\PropertyResolver\EventSelectionPropertyResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_event.property_resolver.event_selection'] = new \Manuxi\SuluEventBundle\Content\PropertyResolver\EventSelectionPropertyResolver();
    }
}
