<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_FieldMetadataValidator_ChainService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.field_metadata_validator.chain' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\Validation\ChainFieldMetadataValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_admin.field_metadata_validator.chain'] = new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\Validation\ChainFieldMetadataValidator(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['sulu_admin.field_metadata_validator.types_property'] ??= new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\Validation\TypesPropertyFieldMetadataValidator());
            yield 1 => ($container->privates['sulu_admin.field_metadata_validator.block'] ??= new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\Validation\BlockFieldMetadataValidator());
            yield 2 => ($container->privates['sulu_media.field_metadata_validator.image_map'] ??= new \Sulu\Bundle\MediaBundle\Metadata\ImageMapFieldMetadataValidator());
        }, 3));
    }
}
