<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_SeoMergerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_content.seo_merger' shared service.
     *
     * @return \Sulu\Content\Application\ContentMerger\Merger\SeoMerger
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_content.seo_merger'] = new \Sulu\Content\Application\ContentMerger\Merger\SeoMerger();
    }
}
