<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_PageAdminService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.page_admin' shared service.
     *
     * @return \Sulu\Page\Infrastructure\Sulu\Admin\PageAdmin
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.page_admin'] = new \Sulu\Page\Infrastructure\Sulu\Admin\PageAdmin(($container->privates['sulu_admin.view_builder_factory'] ??= new \Sulu\Bundle\AdminBundle\Admin\View\ViewBuilderFactory()), ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->load('getSuluCore_Webspace_WebspaceManagerService')), ($container->services['sulu_security.security_checker'] ?? self::getSuluSecurity_SecurityCheckerService($container)), ($container->privates['sulu_content.content_view_builder_factory'] ?? $container->load('getSuluContent_ContentViewBuilderFactoryService')), ($container->privates['sulu_activity.activity_list_view_builder_factory'] ?? $container->load('getSuluActivity_ActivityListViewBuilderFactoryService')));
    }
}
