<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_ContentPersisterService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_content.content_persister' shared service.
     *
     * @return \Sulu\Content\Application\ContentPersister\ContentPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_content.dimension_content_collection_factory'] ?? $container->load('getSuluContent_DimensionContentCollectionFactoryService'));

        if (isset($container->privates['sulu_content.content_persister'])) {
            return $container->privates['sulu_content.content_persister'];
        }

        return $container->privates['sulu_content.content_persister'] = new \Sulu\Content\Application\ContentPersister\ContentPersister($a, ($container->privates['sulu_content.content_merger'] ?? $container->load('getSuluContent_ContentMergerService')));
    }
}
