<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_ContentMetadataInspectorService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_content.content_metadata_inspector' shared service.
     *
     * @return \Sulu\Content\Application\ContentMetadataInspector\ContentMetadataInspector
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sulu_content.content_metadata_inspector'])) {
            return $container->privates['sulu_content.content_metadata_inspector'];
        }

        return $container->privates['sulu_content.content_metadata_inspector'] = new \Sulu\Content\Application\ContentMetadataInspector\ContentMetadataInspector($a);
    }
}
