<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluEvent_SocialShareGeneratorService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_event.social_share_generator' shared service.
     *
     * @return \Manuxi\SuluEventBundle\Service\SocialShareGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_media.media_manager'] ?? $container->load('getSuluMedia_MediaManagerService'));

        if (isset($container->privates['sulu_event.social_share_generator'])) {
            return $container->privates['sulu_event.social_share_generator'];
        }

        return $container->privates['sulu_event.social_share_generator'] = new \Manuxi\SuluEventBundle\Service\SocialShareGenerator(($container->privates['sulu_content.content_aggregator'] ?? $container->load('getSuluContent_ContentAggregatorService')), $a);
    }
}
