<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAudienceTargeting_Rules_QueryStringService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_audience_targeting.rules.query_string' shared service.
     *
     * @return \Sulu\Bundle\AudienceTargetingBundle\Rule\QueryStringRule
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_audience_targeting.rules.query_string'] = new \Sulu\Bundle\AudienceTargetingBundle\Rule\QueryStringRule(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['translator'] ?? self::getTranslatorService($container)), 'X-Forwarded-URL');
    }
}
