<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_AccountManagerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_contact.account_manager' shared service.
     *
     * @return \Sulu\Bundle\ContactBundle\Contact\AccountManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['sulu_contact.account_manager'])) {
            return $container->services['sulu_contact.account_manager'];
        }
        $b = ($container->services['sulu_tag.tag_manager'] ?? $container->load('getSuluTag_TagManagerService'));

        if (isset($container->services['sulu_contact.account_manager'])) {
            return $container->services['sulu_contact.account_manager'];
        }
        $c = ($container->services['sulu_media.media_manager'] ?? $container->load('getSuluMedia_MediaManagerService'));

        if (isset($container->services['sulu_contact.account_manager'])) {
            return $container->services['sulu_contact.account_manager'];
        }
        $d = ($container->privates['sulu_activity.domain_event_collector'] ?? $container->load('getSuluActivity_DomainEventCollectorService'));

        if (isset($container->services['sulu_contact.account_manager'])) {
            return $container->services['sulu_contact.account_manager'];
        }

        return $container->services['sulu_contact.account_manager'] = new \Sulu\Bundle\ContactBundle\Contact\AccountManager($a, $b, $c, ($container->services['sulu_contact.account_factory'] ??= new \Sulu\Bundle\ContactBundle\Contact\AccountFactory('Sulu\\Bundle\\ContactBundle\\Entity\\Account')), ($container->services['sulu.repository.account'] ?? $container->load('getSulu_Repository_AccountService')), ($container->services['sulu.repository.contact'] ?? $container->load('getSulu_Repository_ContactService')), ($container->services['sulu.repository.media'] ?? $container->load('getSulu_Repository_MediaService')), $d, 'Sulu\\Bundle\\ContactBundle\\Entity\\Account');
    }
}
