<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_Webspace_WebspaceManagerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_core.webspace.webspace_manager' shared service.
     *
     * @return \Sulu\Component\Webspace\Manager\WebspaceManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_admin.metadata_provider_registry'] ?? $container->load('getSuluAdmin_MetadataProviderRegistryService'));

        if (isset($container->services['sulu_core.webspace.webspace_manager'])) {
            return $container->services['sulu_core.webspace.webspace_manager'];
        }

        return $container->services['sulu_core.webspace.webspace_manager'] = new \Sulu\Component\Webspace\Manager\WebspaceManager(($container->privates['sulu_core.webspace.loader.delegator'] ?? $container->load('getSuluCore_Webspace_Loader_DelegatorService')), ($container->privates['sulu_core.webspace.webspace_manager.url_replacer'] ??= new \Sulu\Component\Webspace\Url\Replacer()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ['config_dir' => (\dirname(__DIR__, 5).'/config/webspaces'), 'cache_dir' => ($container->targetDir.''.'/sulu'), 'debug' => true, 'cache_class' => 'adminWebspaceCollectionCache', 'base_class' => 'WebspaceCollection'], 'test', ($container->privates['router.request_context'] ?? self::getRouter_RequestContextService($container)), $a);
    }
}
