<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_PagesSitemapProviderService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.pages_sitemap_provider' shared service.
     *
     * @return \Sulu\Page\Infrastructure\Sulu\Sitemap\PagesSitemapProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.pages_sitemap_provider'] = new \Sulu\Page\Infrastructure\Sulu\Sitemap\PagesSitemapProvider(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->load('getSuluCore_Webspace_WebspaceManagerService')), 'test', ($container->privates['sulu_security.access_control_query_enhancer'] ?? self::getSuluSecurity_AccessControlQueryEnhancerService($container)), ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container)), $container->parameters['sulu_security.permissions']);
    }
}
