<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_RequestProcessor_AdminService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_core.request_processor.admin' shared service.
     *
     * @return \Sulu\Component\Webspace\Analyzer\Attributes\AdminRequestProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.request_processor.admin'] = new \Sulu\Component\Webspace\Analyzer\Attributes\AdminRequestProcessor(($container->services['sulu_core.webspace.webspace_manager'] ?? $container->load('getSuluCore_Webspace_WebspaceManagerService')), 'test');
    }
}
