<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_TwoFactorFormMetadataVisitorService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_security.two_factor_form_metadata_visitor' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\Metadata\TwoFactorFormMetadataVisitor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container));

        if (isset($container->privates['sulu_security.two_factor_form_metadata_visitor'])) {
            return $container->privates['sulu_security.two_factor_form_metadata_visitor'];
        }

        return $container->privates['sulu_security.two_factor_form_metadata_visitor'] = new \Sulu\Bundle\SecurityBundle\Metadata\TwoFactorFormMetadataVisitor([], NULL, $a);
    }
}
