<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluRoute_RouteHistoryControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_route.route_history_controller' shared service.
     *
     * @return \Sulu\Route\Userinterface\Controller\Admin\RouteHistoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_route.route_history_controller'] = new \Sulu\Route\Userinterface\Controller\Admin\RouteHistoryController(($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')), ($container->services['sulu_core.list_builder.field_descriptor_factory'] ?? $container->load('getSuluCore_ListBuilder_FieldDescriptorFactoryService')), ($container->services['sulu_core.doctrine_list_builder_factory'] ?? $container->load('getSuluCore_DoctrineListBuilderFactoryService')), ($container->services['sulu_core.doctrine_rest_helper'] ?? $container->load('getSuluCore_DoctrineRestHelperService')));
    }
}
