<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_WebspaceSelectService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_content.webspace_select' shared service.
     *
     * @return \Sulu\Content\Infrastructure\Sulu\Page\Select\WebspaceSelect
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_content.webspace_select'] = new \Sulu\Content\Infrastructure\Sulu\Page\Select\WebspaceSelect(($container->services['sulu_core.webspace.webspace_manager'] ?? $container->load('getSuluCore_Webspace_WebspaceManagerService')));
    }
}
