<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_Analytics_EventSubscriberService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_website.analytics.event_subscriber' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\EventSubscriber\AnalyticsSerializeEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_website.analytics.event_subscriber'] = new \Sulu\Bundle\WebsiteBundle\EventSubscriber\AnalyticsSerializeEventSubscriber();
    }
}
