<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_ContentViewResolverService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_content.content_view_resolver' shared service.
     *
     * @return \Sulu\Content\Application\ContentResolver\ContentViewResolver\ContentViewResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_content.content_view_resolver'] = new \Sulu\Content\Application\ContentResolver\ContentViewResolver\ContentViewResolver(($container->privates['sulu_content.resolvable_resource_queue_processor'] ??= new \Sulu\Content\Application\ContentResolver\ResolvableResourceQueue\ResolvableResourceQueueProcessor()), new RewindableGenerator(function () use ($container) {
            yield 'template' => ($container->privates['sulu_content.template_resolver'] ?? $container->load('getSuluContent_TemplateResolverService'));
            yield 'settings' => ($container->privates['sulu_content.settings_resolver'] ??= new \Sulu\Content\Application\ContentResolver\Resolver\SettingsResolver());
            yield 'excerpt' => ($container->privates['sulu_content.excerpt_taxonomy_resolver'] ?? $container->load('getSuluContent_ExcerptTaxonomyResolverService'));
            yield 'seo' => ($container->privates['sulu_content.seo_resolver'] ?? $container->load('getSuluContent_SeoResolverService'));
            yield 'object' => ($container->privates['sulu_content.dimension_content_resolver'] ?? $container->load('getSuluContent_DimensionContentResolverService'));
        }, 5));
    }
}
