<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_TeaserProviderPoolService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.teaser_provider_pool' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Teaser\Provider\TeaserProviderPool
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_admin.teaser_provider_pool'] = new \Sulu\Bundle\AdminBundle\Teaser\Provider\TeaserProviderPool(new RewindableGenerator(function () use ($container) {
            yield 'pages' => ($container->privates['sulu_page.page_teaser_provider'] ?? $container->load('getSuluPage_PageTeaserProviderService'));
        }, 1));
    }
}
