<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAudienceTargeting_TargetGroupStoreService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_audience_targeting.target_group_store' shared service.
     *
     * @return \Sulu\Bundle\AudienceTargetingBundle\TargetGroup\TargetGroupStore
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_audience_targeting.target_group_store'] = new \Sulu\Bundle\AudienceTargetingBundle\TargetGroup\TargetGroupStore();
    }
}
