<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluTrash_TrashItemRepositoryService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_trash.trash_item_repository' shared service.
     *
     * @return \Sulu\Bundle\TrashBundle\Infrastructure\Doctrine\Repository\TrashItemRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sulu_trash.trash_item_repository'])) {
            return $container->privates['sulu_trash.trash_item_repository'];
        }
        $b = ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container));

        if (isset($container->privates['sulu_trash.trash_item_repository'])) {
            return $container->privates['sulu_trash.trash_item_repository'];
        }

        return $container->privates['sulu_trash.trash_item_repository'] = new \Sulu\Bundle\TrashBundle\Infrastructure\Doctrine\Repository\TrashItemRepository($a, $b);
    }
}
