<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_AccountControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_contact.account_controller' shared service.
     *
     * @return \Sulu\Bundle\ContactBundle\Controller\AccountController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_contact.account_controller'] = new \Sulu\Bundle\ContactBundle\Controller\AccountController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->services['sulu_core.doctrine_rest_helper'] ?? $container->load('getSuluCore_DoctrineRestHelperService')), ($container->services['sulu_core.doctrine_list_builder_factory'] ?? $container->load('getSuluCore_DoctrineListBuilderFactoryService')), ($container->services['sulu_core.list_builder.field_descriptor_factory'] ?? $container->load('getSuluCore_ListBuilder_FieldDescriptorFactoryService')), ($container->services['sulu_media.media_manager'] ?? $container->load('getSuluMedia_MediaManagerService')), ($container->services['sulu.repository.account'] ?? $container->load('getSulu_Repository_AccountService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['sulu_contact.account_manager'] ?? $container->load('getSuluContact_AccountManagerService')), ($container->services['sulu_contact.account_factory'] ??= new \Sulu\Bundle\ContactBundle\Contact\AccountFactory('Sulu\\Bundle\\ContactBundle\\Entity\\Account')), ($container->privates['sulu_activity.domain_event_collector'] ?? $container->load('getSuluActivity_DomainEventCollectorService')), 'Sulu\\Bundle\\ContactBundle\\Entity\\Account', 'Sulu\\Bundle\\ContactBundle\\Entity\\Contact', ($container->privates['sulu_trash.trash_manager'] ?? $container->load('getSuluTrash_TrashManagerService')));
    }
}
