<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMarkup_ParserService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_markup.parser' shared service.
     *
     * @return \Sulu\Bundle\MarkupBundle\Markup\HtmlMarkupParser
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_markup.parser'] = new \Sulu\Bundle\MarkupBundle\Markup\HtmlMarkupParser(($container->privates['sulu_markup.tag.registry'] ?? $container->load('getSuluMarkup_Tag_RegistryService')), ($container->privates['sulu_markup.parser.delegating_html_extractor'] ?? $container->load('getSuluMarkup_Parser_DelegatingHtmlExtractorService')));
    }
}
