<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAudienceTargeting_AdminService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_audience_targeting.admin' shared service.
     *
     * @return \Sulu\Bundle\AudienceTargetingBundle\Admin\AudienceTargetingAdmin
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_audience_targeting.admin'] = new \Sulu\Bundle\AudienceTargetingBundle\Admin\AudienceTargetingAdmin(($container->privates['sulu_admin.view_builder_factory'] ??= new \Sulu\Bundle\AdminBundle\Admin\View\ViewBuilderFactory()), ($container->privates['sulu_audience_targeting.rules_collection'] ?? $container->load('getSuluAudienceTargeting_RulesCollectionService')), ($container->services['sulu_security.security_checker'] ?? self::getSuluSecurity_SecurityCheckerService($container)));
    }
}
