<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluReference_ReferenceRepositoryService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_reference.reference_repository' shared service.
     *
     * @return \Sulu\Bundle\ReferenceBundle\Infrastructure\Doctrine\Repository\ReferenceRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sulu_reference.reference_repository'])) {
            return $container->privates['sulu_reference.reference_repository'];
        }

        return $container->privates['sulu_reference.reference_repository'] = new \Sulu\Bundle\ReferenceBundle\Infrastructure\Doctrine\Repository\ReferenceRepository($a);
    }
}
