<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_PageExcerptNormalizerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.page_excerpt_normalizer' shared service.
     *
     * @return \Sulu\Page\Infrastructure\Sulu\Content\Normalizer\PageExcerptNormalizer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.page_excerpt_normalizer'] = new \Sulu\Page\Infrastructure\Sulu\Content\Normalizer\PageExcerptNormalizer();
    }
}
