<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluEvent_Command_GenerateRecurringService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_event.command.generate_recurring' shared service.
     *
     * @return \Manuxi\SuluEventBundle\Command\GenerateRecurringEventsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_event.command.generate_recurring'] = $instance = new \Manuxi\SuluEventBundle\Command\GenerateRecurringEventsCommand(($container->services['Manuxi\\SuluEventBundle\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')), ($container->privates['sulu_event.recurrence_generator'] ??= new \Manuxi\SuluEventBundle\Service\RecurrenceGenerator()), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['sulu_content.content_manager'] ?? $container->load('getSuluContent_ContentManagerService')));

        $instance->setName('sulu:events:generate-recurring');
        $instance->setDescription('Generate upcoming occurrences for recurring events');

        return $instance;
    }
}
