<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPreview_PreviewObjectProviderRegistryService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_preview.preview_object_provider_registry' shared service.
     *
     * @return \Sulu\Bundle\PreviewBundle\Preview\Object\PreviewObjectProviderRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_preview.preview_object_provider_registry'] = new \Sulu\Bundle\PreviewBundle\Preview\Object\PreviewObjectProviderRegistry(new RewindableGenerator(function () use ($container) {
            yield 'pages' => ($container->privates['sulu_page.page_preview_provider'] ?? $container->load('getSuluPage_PagePreviewProviderService'));
            yield 'events' => ($container->privates['sulu_event.preview_object_provider'] ?? $container->load('getSuluEvent_PreviewObjectProviderService'));
        }, 2));
    }
}
