<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_DebugViewCommandService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.debug_view_command' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Command\ViewDebugCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_admin.debug_view_command'] = $instance = new \Sulu\Bundle\AdminBundle\Command\ViewDebugCommand(($container->privates['sulu_admin.view_registry'] ?? $container->load('getSuluAdmin_ViewRegistryService')));

        $instance->setName('sulu:admin:debug-view');
        $instance->setDescription('Display current Views for the admin');

        return $instance;
    }
}
