<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Command_InitializeHomepageService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.command.initialize_homepage' shared service.
     *
     * @return \Sulu\Page\UserInterface\Command\InitializeHomepageCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_page.command.initialize_homepage'] = $instance = new \Sulu\Page\UserInterface\Command\InitializeHomepageCommand(($container->services['sulu_core.webspace.webspace_manager'] ?? $container->load('getSuluCore_Webspace_WebspaceManagerService')), ($container->privates['sulu_page.page_repository'] ?? self::getSuluPage_PageRepositoryService($container)), ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')));

        $instance->setName('sulu:page:initialize');
        $instance->setDescription('Initializes the homepage per webspace locale');

        return $instance;
    }
}
