<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_MediaRedirectControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_media.media_redirect_controller' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Controller\MediaRedirectController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_media.media_redirect_controller'] = new \Sulu\Bundle\MediaBundle\Controller\MediaRedirectController(($container->services['sulu_media.media_manager'] ?? $container->load('getSuluMedia_MediaManagerService')));
    }
}
