<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_AccountListenerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_contact.account_listener' shared service.
     *
     * @return \Sulu\Bundle\ContactBundle\EventListener\AccountListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_contact.account_listener'] = new \Sulu\Bundle\ContactBundle\EventListener\AccountListener();
    }
}
