<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCategory_KeywordControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_category.keyword_controller' shared service.
     *
     * @return \Sulu\Bundle\CategoryBundle\Controller\KeywordController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_category.keyword_controller'] = new \Sulu\Bundle\CategoryBundle\Controller\KeywordController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sulu_core.doctrine_rest_helper'] ?? $container->load('getSuluCore_DoctrineRestHelperService')), ($container->services['sulu_core.doctrine_list_builder_factory'] ?? $container->load('getSuluCore_DoctrineListBuilderFactoryService')), ($container->services['sulu_core.list_builder.field_descriptor_factory'] ?? $container->load('getSuluCore_ListBuilder_FieldDescriptorFactoryService')), ($container->services['sulu_category.keyword_manager'] ?? $container->load('getSuluCategory_KeywordManagerService')), ($container->services['sulu.repository.keyword'] ?? $container->load('getSulu_Repository_KeywordService')), ($container->services['sulu.repository.category'] ?? $container->load('getSulu_Repository_CategoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), 'Sulu\\Bundle\\CategoryBundle\\Entity\\Keyword');
    }
}
