<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_UpdateBuildCommandService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.update_build_command' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Command\UpdateBuildCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_admin.update_build_command'] = $instance = new \Sulu\Bundle\AdminBundle\Command\UpdateBuildCommand(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), \dirname(__DIR__, 5), '_._._');

        $instance->setName('sulu:admin:update-build');
        $instance->setDescription('Updates the administration application JavaScript build by downloading the official build from the sulu/skeleton repository or building the assets via npm.');

        return $instance;
    }
}
