<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_IconProvider_IcomoonService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.icon_provider.icomoon' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Icon\providers\IcomoonProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_admin.icon_provider.icomoon'] = new \Sulu\Bundle\AdminBundle\Icon\providers\IcomoonProvider();
    }
}
