<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authenticator_HttpBasic_TestService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'security.authenticator.http_basic.test' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authenticator\HttpBasicAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['test_user_provider'] ?? $container->load('getTestUserProviderService'));

        if (isset($container->privates['security.authenticator.http_basic.test'])) {
            return $container->privates['security.authenticator.http_basic.test'];
        }

        return $container->privates['security.authenticator.http_basic.test'] = new \Symfony\Component\Security\Http\Authenticator\HttpBasicAuthenticator('Secured Area', $a, ($container->privates['logger'] ?? self::getLoggerService($container)));
    }
}
