<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_CollectionControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_media.collection_controller' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Controller\CollectionController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_media.collection_controller'] = new \Sulu\Bundle\MediaBundle\Controller\CollectionController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->services['sulu_core.list_rest_helper'] ?? $container->load('getSuluCore_ListRestHelperService')), ($container->services['sulu_security.security_checker'] ?? self::getSuluSecurity_SecurityCheckerService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['sulu_media.system_collections.manager'] ?? $container->load('getSuluMedia_SystemCollections_ManagerService')), ($container->services['sulu_media.collection_manager'] ?? $container->load('getSuluMedia_CollectionManagerService')), $container->parameters['sulu_media.collection.type.default'], $container->parameters['sulu_security.permissions'], 'Sulu\\Bundle\\MediaBundle\\Entity\\Collection');
    }
}
