<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAudienceTargeting_TargetGroupControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_audience_targeting.target_group_controller' shared service.
     *
     * @return \Sulu\Bundle\AudienceTargetingBundle\Controller\TargetGroupController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_audience_targeting.target_group_controller'] = new \Sulu\Bundle\AudienceTargetingBundle\Controller\TargetGroupController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sulu_core.doctrine_rest_helper'] ?? $container->load('getSuluCore_DoctrineRestHelperService')), ($container->services['sulu_core.list_builder.field_descriptor_factory'] ?? $container->load('getSuluCore_ListBuilder_FieldDescriptorFactoryService')), ($container->services['sulu_core.doctrine_list_builder_factory'] ?? $container->load('getSuluCore_DoctrineListBuilderFactoryService')), ($container->services['sulu.repository.target_group'] ?? $container->load('getSulu_Repository_TargetGroupService')), ($container->services['sulu.repository.target_group_rule'] ?? $container->load('getSulu_Repository_TargetGroupRuleService')), ($container->services['sulu.repository.target_group_condition'] ?? $container->load('getSulu_Repository_TargetGroupConditionService')), ($container->services['sulu.repository.target_group_webspace'] ?? $container->load('getSulu_Repository_TargetGroupWebspaceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
