<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_SmartContentSmartResolverService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_content.smart_content_smart_resolver' shared service.
     *
     * @return \Sulu\Content\Application\SmartResolver\Resolver\SmartContentSmartResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.mklIyIq'] ?? $container->load('get_ServiceLocator_MklIyIqService'));

        if (isset($container->privates['sulu_content.smart_content_smart_resolver'])) {
            return $container->privates['sulu_content.smart_content_smart_resolver'];
        }

        return $container->privates['sulu_content.smart_content_smart_resolver'] = new \Sulu\Content\Application\SmartResolver\Resolver\SmartContentSmartResolver($a, ($container->services['sulu_audience_targeting.target_group_store'] ??= new \Sulu\Bundle\AudienceTargetingBundle\TargetGroup\TargetGroupStore()));
    }
}
