<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_SeoInstanceofFormMetadataVisitorService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_content.seo_instanceof_form_metadata_visitor' shared service.
     *
     * @return \Sulu\Content\Infrastructure\Sulu\Form\InstanceOfFormMetadataVisitor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_content.seo_instanceof_form_metadata_visitor'] = new \Sulu\Content\Infrastructure\Sulu\Form\InstanceOfFormMetadataVisitor(($container->privates['sulu_admin.xml_form_metadata_loader'] ?? $container->load('getSuluAdmin_XmlFormMetadataLoaderService')), 'content_seo', $container->parameters['sulu_content.content_seo_forms']);
    }
}
