<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluActivity_DomainEventDispatcherService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_activity.domain_event_dispatcher' shared service.
     *
     * @return \Sulu\Bundle\ActivityBundle\Application\Dispatcher\DomainEventDispatcher
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['sulu_activity.domain_event_dispatcher'])) {
            return $container->privates['sulu_activity.domain_event_dispatcher'];
        }

        return $container->privates['sulu_activity.domain_event_dispatcher'] = new \Sulu\Bundle\ActivityBundle\Application\Dispatcher\DomainEventDispatcher($a);
    }
}
