<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_MediaTrashItemHandlerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_media.media_trash_item_handler' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Trash\MediaTrashItemHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_trash.trash_item_repository'] ?? $container->load('getSuluTrash_TrashItemRepositoryService'));

        if (isset($container->privates['sulu_media.media_trash_item_handler'])) {
            return $container->privates['sulu_media.media_trash_item_handler'];
        }
        $b = ($container->services['sulu.repository.media'] ?? $container->load('getSulu_Repository_MediaService'));

        if (isset($container->privates['sulu_media.media_trash_item_handler'])) {
            return $container->privates['sulu_media.media_trash_item_handler'];
        }
        $c = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sulu_media.media_trash_item_handler'])) {
            return $container->privates['sulu_media.media_trash_item_handler'];
        }
        $d = ($container->privates['sulu_activity.domain_event_collector'] ?? $container->load('getSuluActivity_DomainEventCollectorService'));

        if (isset($container->privates['sulu_media.media_trash_item_handler'])) {
            return $container->privates['sulu_media.media_trash_item_handler'];
        }

        return $container->privates['sulu_media.media_trash_item_handler'] = new \Sulu\Bundle\MediaBundle\Trash\MediaTrashItemHandler($a, $b, $c, ($container->privates['sulu_trash.doctrine_restore_helper'] ?? $container->load('getSuluTrash_DoctrineRestoreHelperService')), $d, ($container->services['sulu_media.storage'] ?? $container->load('getSuluMedia_StorageService')));
    }
}
