<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMessenger_LockMiddlewareService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_messenger.lock_middleware' shared service.
     *
     * @return \Sulu\Messenger\Infrastructure\Symfony\Messenger\LockMiddleware\LockMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_messenger.lock_middleware'] = new \Sulu\Messenger\Infrastructure\Symfony\Messenger\LockMiddleware\LockMiddleware((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lock.factory' => ['privates', 'lock.default.factory', 'getLock_Default_FactoryService', true],
        ], [
            'lock.factory' => '?',
        ]))->withContext('sulu_messenger.lock_middleware', $container));
    }
}
