<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMarkup_MailerListenerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_markup.mailer_listener' shared service.
     *
     * @return \Sulu\Bundle\MarkupBundle\Listener\MailerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_markup.mailer_listener'] = new \Sulu\Bundle\MarkupBundle\Listener\MailerListener(($container->privates['sulu_markup.parser'] ?? $container->load('getSuluMarkup_ParserService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), 'en');
    }
}
