<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMarkup_LinkTag_ProviderPoolService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_markup.link_tag.provider_pool' shared service.
     *
     * @return \Sulu\Bundle\MarkupBundle\Markup\Link\LinkProviderPool
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_markup.link_tag.provider_pool'] = new \Sulu\Bundle\MarkupBundle\Markup\Link\LinkProviderPool(new RewindableGenerator(function () use ($container) {
            yield 'media' => ($container->privates['sulu_media.media_link_provider'] ?? $container->load('getSuluMedia_MediaLinkProviderService'));
            yield 'external' => ($container->privates['sulu_markup.external_link_provider'] ?? $container->load('getSuluMarkup_ExternalLinkProviderService'));
            yield 'page' => ($container->privates['sulu_page.page_link_provider'] ?? $container->load('getSuluPage_PageLinkProviderService'));
            yield 'event' => ($container->privates['sulu_event.link_provider'] ?? $container->load('getSuluEvent_LinkProviderService'));
        }, 4));
    }
}
