<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_AdminPageControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_page.admin_page_controller' shared service.
     *
     * @return \Sulu\Page\UserInterface\Controller\Admin\PageController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_page.admin_page_controller'] = new \Sulu\Page\UserInterface\Controller\Admin\PageController(($container->privates['sulu_page.page_repository'] ?? self::getSuluPage_PageRepositoryService($container)), ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')), ($container->privates['serializer'] ?? self::getSerializerService($container)), ($container->privates['sulu_content.content_manager'] ?? $container->load('getSuluContent_ContentManagerService')), ($container->services['sulu_core.list_builder.field_descriptor_factory'] ?? $container->load('getSuluCore_ListBuilder_FieldDescriptorFactoryService')), ($container->services['sulu_core.doctrine_list_builder_factory'] ?? $container->load('getSuluCore_DoctrineListBuilderFactoryService')), ($container->services['sulu_core.doctrine_rest_helper'] ?? $container->load('getSuluCore_DoctrineRestHelperService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['sulu_security.access_control_manager'] ?? $container->load('getSuluSecurity_AccessControlManagerService')), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)));
    }
}
