<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluEvent_TrashItemHandlerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_event.trash_item_handler' shared service.
     *
     * @return \Manuxi\SuluEventBundle\Trash\EventTrashItemHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_trash.trash_item_repository'] ?? $container->load('getSuluTrash_TrashItemRepositoryService'));

        if (isset($container->privates['sulu_event.trash_item_handler'])) {
            return $container->privates['sulu_event.trash_item_handler'];
        }
        $b = ($container->privates['sulu_content.content_normalizer'] ?? $container->load('getSuluContent_ContentNormalizerService'));

        if (isset($container->privates['sulu_event.trash_item_handler'])) {
            return $container->privates['sulu_event.trash_item_handler'];
        }
        $c = ($container->privates['sulu_activity.domain_event_collector'] ?? $container->load('getSuluActivity_DomainEventCollectorService'));

        if (isset($container->privates['sulu_event.trash_item_handler'])) {
            return $container->privates['sulu_event.trash_item_handler'];
        }

        return $container->privates['sulu_event.trash_item_handler'] = new \Manuxi\SuluEventBundle\Trash\EventTrashItemHandler($a, ($container->services['Manuxi\\SuluEventBundle\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')), $b, ($container->privates['sulu_content.content_merger'] ?? $container->load('getSuluContent_ContentMergerService')), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['sulu_event.event_mapper'] ?? $container->load('getSuluEvent_EventMapperService'));
        }, 1), $c);
    }
}
