<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_LogoutEventSubscriberService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_security.logout_event_subscriber' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\EventListener\LogoutEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->privates['sulu_security.logout_event_subscriber'])) {
            return $container->privates['sulu_security.logout_event_subscriber'];
        }

        return $container->privates['sulu_security.logout_event_subscriber'] = new \Sulu\Bundle\SecurityBundle\EventListener\LogoutEventSubscriber($a);
    }
}
