<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_RequestProcessor_DateTimeService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_core.request_processor.date_time' shared service.
     *
     * @return \Sulu\Component\Webspace\Analyzer\Attributes\DateTimeRequestProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.request_processor.date_time'] = new \Sulu\Component\Webspace\Analyzer\Attributes\DateTimeRequestProcessor();
    }
}
