<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_ContentControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_content.content_controller' shared service.
     *
     * @return \Sulu\Content\UserInterface\Controller\Website\ContentController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['sulu_content.content_controller'] = $instance = new \Sulu\Content\UserInterface\Controller\Website\ContentController();

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'router' => ['services', 'router', 'getRouterService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'security.authorization_checker' => ['services', 'jms_serializer.authorization_checker', 'getJmsSerializer_AuthorizationCheckerService', false],
            'twig' => ['privates', 'twig', 'getTwigService', true],
            'security.token_storage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'security.csrf.token_manager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'sulu_content.content_resolver' => ['services', 'sulu_content.content_resolver', 'getSuluContent_ContentResolverService', true],
            'sulu_http_cache.cache_lifetime.enhancer' => ['services', 'sulu_http_cache.cache_lifetime.enhancer', 'getSuluHttpCache_CacheLifetime_EnhancerService', true],
            'sulu_route.route_repository' => ['services', 'Sulu\\Route\\Domain\\Repository\\RouteRepositoryInterface', 'getRouteRepositoryInterfaceService', true],
            'sulu_route.route_generator' => ['services', 'Sulu\\Route\\Application\\Routing\\Generator\\RouteGeneratorInterface', 'getRouteGeneratorInterfaceService', true],
            'sulu_core.webspace.webspace_manager' => ['services', 'sulu_core.webspace.webspace_manager', 'getSuluCore_Webspace_WebspaceManagerService', true],
        ], [
            'router' => '?',
            'request_stack' => '?',
            'http_kernel' => '?',
            'serializer' => '?',
            'security.authorization_checker' => '?',
            'twig' => '?',
            'security.token_storage' => '?',
            'security.csrf.token_manager' => '?',
            'parameter_bag' => '?',
            'sulu_content.content_resolver' => '?',
            'sulu_http_cache.cache_lifetime.enhancer' => '?',
            'sulu_route.route_repository' => '?',
            'sulu_route.route_generator' => '?',
            'sulu_core.webspace.webspace_manager' => '?',
        ]))->withContext('sulu_content.content_controller', $container));

        return $instance;
    }
}
