<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCategory_CategoryResourceLoader_Cached_InnerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_category.category_resource_loader.cached.inner' shared service.
     *
     * @return \Sulu\Bundle\CategoryBundle\Infrastructure\Sulu\Content\ResourceLoader\CategoryResourceLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_category.category_manager'] ?? $container->load('getSuluCategory_CategoryManagerService'));

        if (isset($container->privates['sulu_category.category_resource_loader.cached.inner'])) {
            return $container->privates['sulu_category.category_resource_loader.cached.inner'];
        }

        return $container->privates['sulu_category.category_resource_loader.cached.inner'] = new \Sulu\Bundle\CategoryBundle\Infrastructure\Sulu\Content\ResourceLoader\CategoryResourceLoader($a);
    }
}
