<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_MediaFormatControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_media.media_format_controller' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Controller\MediaFormatController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_media.media_format_controller'] = new \Sulu\Bundle\MediaBundle\Controller\MediaFormatController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sulu_media.format_options_manager'] ?? $container->load('getSuluMedia_FormatOptionsManagerService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
