<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_XmlFormMetadataLoaderService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.xml_form_metadata_loader' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\XmlFormMetadataLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_admin.xml_form_metadata_loader'] = new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\XmlFormMetadataLoader(($container->privates['sulu_admin.form_metadata.form_xml_loader'] ?? $container->load('getSuluAdmin_FormMetadata_FormXmlLoaderService')), ($container->privates['sulu_admin.field_metadata_validator.chain'] ?? $container->load('getSuluAdmin_FieldMetadataValidator_ChainService')), $container->parameters['sulu_admin.forms.directories'], ($container->targetDir.''.'/sulu/forms'), true);
    }
}
