<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_EventSubscriber_CacheClearService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_website.event_subscriber.cache_clear' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\EventSubscriber\DomainEventEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_activity.domain_event_dispatcher'] ?? $container->load('getSuluActivity_DomainEventDispatcherService'));

        if (isset($container->privates['sulu_website.event_subscriber.cache_clear'])) {
            return $container->privates['sulu_website.event_subscriber.cache_clear'];
        }

        return $container->privates['sulu_website.event_subscriber.cache_clear'] = new \Sulu\Bundle\WebsiteBundle\EventSubscriber\DomainEventEventSubscriber($a, ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->load('getSuluCore_Webspace_WebspaceManagerService')));
    }
}
