<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_DownloadLanguageCommandService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_admin.download_language_command' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Command\DownloadLanguageCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_admin.download_language_command'] = $instance = new \Sulu\Bundle\AdminBundle\Command\DownloadLanguageCommand(($container->privates['sulu_admin.http_client'] ?? $container->load('getSuluAdmin_HttpClientService')), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()), \dirname(__DIR__, 5), $container->parameters['sulu_core.locales']);

        $instance->setName('sulu:admin:download-language');
        $instance->setDescription('Downloads the currently approved translations for the given language.');

        return $instance;
    }
}
