<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluRoute_RouteHistoryDefaultsProviderService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_route.route_history_defaults_provider' shared service.
     *
     * @return \Sulu\Route\Application\Routing\Matcher\RouteHistoryDefaultsProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_route.route_history_defaults_provider'] = new \Sulu\Route\Application\Routing\Matcher\RouteHistoryDefaultsProvider(($container->services['Sulu\\Route\\Domain\\Repository\\RouteRepositoryInterface'] ?? $container->load('getRouteRepositoryInterfaceService')), ($container->services['Sulu\\Route\\Application\\Routing\\Generator\\RouteGeneratorInterface'] ?? $container->load('getRouteGeneratorInterfaceService')));
    }
}
