<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_BlockIdControllerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_admin.block_id_controller' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Controller\BlockIdController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_admin.block_id_controller'] = new \Sulu\Bundle\AdminBundle\Controller\BlockIdController(($container->privates['sulu_admin.block_id_generator'] ??= new \Sulu\Bundle\AdminBundle\Application\BlockIdGenerator\BlockIdGenerator()));
    }
}
