<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_DispositionType_ResolverService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sulu_media.disposition_type.resolver' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Media\DispositionType\DispositionTypeResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_media.disposition_type.resolver'] = new \Sulu\Bundle\MediaBundle\Media\DispositionType\DispositionTypeResolver('attachment', [], []);
    }
}
