<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_PageLinkProviderService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.page_link_provider' shared service.
     *
     * @return \Sulu\Page\Infrastructure\Sulu\Content\PageLinkProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_content.content_enhancer'] ?? $container->load('getSuluContent_ContentEnhancerService'));

        if (isset($container->privates['sulu_page.page_link_provider'])) {
            return $container->privates['sulu_page.page_link_provider'];
        }

        return $container->privates['sulu_page.page_link_provider'] = new \Sulu\Page\Infrastructure\Sulu\Content\PageLinkProvider(($container->privates['sulu_content.content_aggregator'] ?? $container->load('getSuluContent_ContentAggregatorService')), $a, ($container->privates['sulu_page.page_repository'] ?? self::getSuluPage_PageRepositoryService($container)), ($container->privates['sulu_http_cache.reference_store'] ??= new \Sulu\Bundle\HttpCacheBundle\ReferenceStore\ReferenceStore()), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
