<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_AuthorNormalizerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_content.author_normalizer' shared service.
     *
     * @return \Sulu\Content\Application\ContentNormalizer\Normalizer\AuthorNormalizer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_content.author_normalizer'] = new \Sulu\Content\Application\ContentNormalizer\Normalizer\AuthorNormalizer();
    }
}
