<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_Build_Builder_DatabaseService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_core.build.builder.database' shared service.
     *
     * @return \Sulu\Bundle\CoreBundle\Build\DatabaseBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.build.builder.database'] = new \Sulu\Bundle\CoreBundle\Build\DatabaseBuilder();
    }
}
