<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingsControllersetViewHandlerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.g2zSUIo.Manuxi\SuluEventBundle\Controller\Admin\SettingsController::setViewHandler()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g2zSUIo.Manuxi\\SuluEventBundle\\Controller\\Admin\\SettingsController::setViewHandler()'] = ($container->privates['.service_locator.g2zSUIo'] ?? $container->load('get_ServiceLocator_G2zSUIoService'))->withContext('Manuxi\\SuluEventBundle\\Controller\\Admin\\SettingsController::setViewHandler()', $container);
    }
}
