<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluEvent_PreviewObjectProviderService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_event.preview_object_provider' shared service.
     *
     * @return \Manuxi\SuluEventBundle\Preview\EventObjectProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_event.preview_object_provider'] = new \Manuxi\SuluEventBundle\Preview\EventObjectProvider(($container->services['Manuxi\\SuluEventBundle\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')), ($container->privates['sulu_content.content_aggregator'] ?? $container->load('getSuluContent_ContentAggregatorService')));
    }
}
