<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAudienceTargeting_DeviceDetectorService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_audience_targeting.device_detector' shared service.
     *
     * @return \DeviceDetector\DeviceDetector
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_audience_targeting.device_detector'] = $instance = new \DeviceDetector\DeviceDetector();

        $instance->setCache(new \DeviceDetector\Cache\PSR6Bridge(($container->services['cache.system'] ?? $container->load('getCache_SystemService'))));

        return $instance;
    }
}
