<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_Command_CreateRoleService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_security.command.create_role' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\Command\CreateRoleCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_security.command.create_role'] = $instance = new \Sulu\Bundle\SecurityBundle\Command\CreateRoleCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['sulu.repository.role'] ?? self::getSulu_Repository_RoleService($container)), ($container->services['sulu_admin.admin_pool'] ?? $container->load('getSuluAdmin_AdminPoolService')));

        $instance->setName('sulu:security:role:create');
        $instance->setDescription('Create a role.');

        return $instance;
    }
}
