<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_RouteDataMapperService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_content.route_data_mapper' shared service.
     *
     * @return \Sulu\Content\Application\ContentDataMapper\DataMapper\RoutableDataMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_content.route_data_mapper'] = new \Sulu\Content\Application\ContentDataMapper\DataMapper\RoutableDataMapper(($container->services['Sulu\\Route\\Domain\\Repository\\RouteRepositoryInterface'] ?? $container->load('getRouteRepositoryInterfaceService')), ($container->privates['sulu_admin.metadata_provider_registry'] ?? $container->load('getSuluAdmin_MetadataProviderRegistryService')));
    }
}
