<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContent_PropertyResolverProviderService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_content.property_resolver_provider' shared service.
     *
     * @return \Sulu\Content\Application\PropertyResolver\PropertyResolverProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_content.property_resolver_provider'] = new \Sulu\Content\Application\PropertyResolver\PropertyResolverProvider(new RewindableGenerator(function () use ($container) {
            yield 'account_selection' => ($container->privates['sulu_contact.account_selection_property_resolver'] ??= new \Sulu\Bundle\ContactBundle\Infrastructure\Sulu\Content\PropertyResolver\AccountSelectionPropertyResolver());
            yield 'single_account_selection' => ($container->privates['sulu_contact.single_account_selection_property_resolver'] ??= new \Sulu\Bundle\ContactBundle\Infrastructure\Sulu\Content\PropertyResolver\SingleAccountSelectionPropertyResolver());
            yield 'contact_selection' => ($container->privates['sulu_contact.contact_selection_property_resolver'] ??= new \Sulu\Bundle\ContactBundle\Infrastructure\Sulu\Content\PropertyResolver\ContactSelectionPropertyResolver());
            yield 'single_contact_selection' => ($container->privates['sulu_contact.single_contact_selection_property_resolver'] ??= new \Sulu\Bundle\ContactBundle\Infrastructure\Sulu\Content\PropertyResolver\SingleContactSelectionPropertyResolver());
            yield 'contact_account_selection' => ($container->privates['sulu_contact.account_contact_selection_property_resolver'] ??= new \Sulu\Bundle\ContactBundle\Infrastructure\Sulu\Content\PropertyResolver\ContactAccountSelectionPropertyResolver());
            yield 'tag_selection' => ($container->privates['sulu_tag.tag_selection_property_resolver'] ??= new \Sulu\Bundle\TagBundle\Infrastructure\Sulu\Content\PropertyResolver\TagSelectionPropertyResolver());
            yield 'media_selection' => ($container->privates['sulu_media.media_selection_property_resolver'] ??= new \Sulu\Bundle\MediaBundle\Infrastructure\Sulu\Content\PropertyResolver\MediaSelectionPropertyResolver());
            yield 'single_media_selection' => ($container->privates['sulu_media.single_media_selection_property_resolver'] ??= new \Sulu\Bundle\MediaBundle\Infrastructure\Sulu\Content\PropertyResolver\SingleMediaSelectionPropertyResolver());
            yield 'image_map' => ($container->privates['sulu_media.image_map_property_resolver'] ?? $container->load('getSuluMedia_ImageMapPropertyResolverService'));
            yield 'collection_selection' => ($container->privates['sulu_media.collection_selection_property_resolver'] ??= new \Sulu\Bundle\MediaBundle\Infrastructure\Sulu\Content\PropertyResolver\CollectionSelectionPropertyResolver());
            yield 'single_collection_selection' => ($container->privates['sulu_media.single_collection_selection_property_resolver'] ??= new \Sulu\Bundle\MediaBundle\Infrastructure\Sulu\Content\PropertyResolver\SingleCollectionSelectionPropertyResolver());
            yield 'category_selection' => ($container->privates['sulu_category.category_selection_property_resolver'] ??= new \Sulu\Bundle\CategoryBundle\Infrastructure\Sulu\Content\PropertyResolver\CategorySelectionPropertyResolver());
            yield 'single_category_selection' => ($container->privates['sulu_category.single_category_selection_property_resolver'] ??= new \Sulu\Bundle\CategoryBundle\Infrastructure\Sulu\Content\PropertyResolver\SingleCategorySelectionPropertyResolver());
            yield 'default' => ($container->privates['sulu_content.default_property_resolver'] ??= new \Sulu\Content\Application\PropertyResolver\Resolver\DefaultPropertyResolver());
            yield 'block' => ($container->privates['sulu_content.block_property_resolver'] ?? $container->load('getSuluContent_BlockPropertyResolverService'));
            yield 'link' => ($container->privates['sulu_content.link_property_resolver'] ??= new \Sulu\Content\Application\PropertyResolver\Resolver\LinkPropertyResolver());
            yield 'teaser_selection' => ($container->privates['sulu_content.teaser_selection_property_resolver'] ??= new \Sulu\Content\Application\PropertyResolver\Resolver\TeaserSelectionPropertyResolver());
            yield 'date' => ($container->privates['sulu_content.date_property_resolver'] ??= new \Sulu\Content\Application\PropertyResolver\Resolver\DatePropertyResolver());
            yield 'datetime' => ($container->privates['sulu_content.datetime_property_resolver'] ??= new \Sulu\Content\Application\PropertyResolver\Resolver\DateTimePropertyResolver());
            yield 'smart_content' => ($container->privates['sulu_content.smart_content_property_resolver'] ?? $container->load('getSuluContent_SmartContentPropertyResolverService'));
            yield 'page_selection' => ($container->privates['sulu_page.page_selection_property_resolver'] ??= new \Sulu\Page\Infrastructure\Sulu\Content\PropertyResolver\PageSelectionPropertyResolver());
            yield 'single_page_selection' => ($container->privates['sulu_page.single_page_selection_property_resolver'] ??= new \Sulu\Page\Infrastructure\Sulu\Content\PropertyResolver\SinglePageSelectionPropertyResolver());
            yield 'page_tree_route' => ($container->privates['sulu_page.page_tree_route_property_resolver'] ??= new \Sulu\Page\Infrastructure\Sulu\Content\PropertyResolver\PageTreeRoutePropertyResolver());
            yield 'single_event_selection' => ($container->privates['sulu_event.property_resolver.single_event_selection'] ??= new \Manuxi\SuluEventBundle\Content\PropertyResolver\SingleEventSelectionPropertyResolver());
            yield 'event_selection' => ($container->privates['sulu_event.property_resolver.event_selection'] ??= new \Manuxi\SuluEventBundle\Content\PropertyResolver\EventSelectionPropertyResolver());
            yield 'event_calendar' => ($container->privates['sulu_event.property_resolver.event_calendar'] ??= new \Manuxi\SuluEventBundle\Content\PropertyResolver\EventCalendarPropertyResolver());
            yield 'single_location_selection' => ($container->privates['sulu_event.property_resolver.single_location_selection'] ??= new \Manuxi\SuluEventBundle\Content\PropertyResolver\SingleLocationSelectionPropertyResolver());
        }, 27));
    }
}
