<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_Image_MediaExtractorService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_media.image.media_extractor' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Media\ImageConverter\MediaImageExtractor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_media.image.media_extractor'] = new \Sulu\Bundle\MediaBundle\Media\ImageConverter\MediaImageExtractor(($container->privates['sulu_media.adapter.gd'] ??= new \Imagine\Gd\Imagine()), ($container->privates['sulu_media.video_thumbnail_generator'] ??= new \Sulu\Bundle\MediaBundle\Media\Video\VideoThumbnailService(NULL)), 'gs');
    }
}
