<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_WebsitePageReindexProviderService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sulu_page.website_page_reindex_provider' shared service.
     *
     * @return \Sulu\Page\Infrastructure\Sulu\Search\WebsitePageReindexProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sulu_page.website_page_reindex_provider'])) {
            return $container->privates['sulu_page.website_page_reindex_provider'];
        }

        return $container->privates['sulu_page.website_page_reindex_provider'] = new \Sulu\Page\Infrastructure\Sulu\Search\WebsitePageReindexProvider($a, new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['sulu_page.website_page_reindex_content_enhancer'] ?? $container->load('getSuluPage_WebsitePageReindexContentEnhancerService'));
        }, 1));
    }
}
