<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Extension_HtmlsanitizerService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'twig.extension.htmlsanitizer' shared service.
     *
     * @return \Symfony\Bridge\Twig\Extension\HtmlSanitizerExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['twig.extension.htmlsanitizer'] = new \Symfony\Bridge\Twig\Extension\HtmlSanitizerExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'default' => ['privates', 'html_sanitizer.sanitizer.default', 'getHtmlSanitizer_Sanitizer_DefaultService', true],
        ], [
            'default' => 'Symfony\\Component\\HtmlSanitizer\\HtmlSanitizer',
        ]));
    }
}
