<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_ValidatorService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'twig.validator' shared service.
     *
     * @return \Symfony\Bridge\Twig\Validator\Constraints\TwigValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['twig'] ?? $container->load('getTwigService'));

        if (isset($container->privates['twig.validator'])) {
            return $container->privates['twig.validator'];
        }

        return $container->privates['twig.validator'] = new \Symfony\Bridge\Twig\Validator\Constraints\TwigValidator($a);
    }
}
