<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwigService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'twig' shared service.
     *
     * @return \Twig\Environment
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['twig'] = $instance = new \Twig\Environment(($container->privates['twig.loader.native_filesystem'] ?? $container->load('getTwig_Loader_NativeFilesystemService')), ['cache' => ($container->targetDir.''.'/twig'), 'charset' => 'UTF-8', 'debug' => true, 'strict_variables' => true, 'autoescape' => 'name']);

        $instance->addExtension(($container->privates['twig.extension.security_csrf'] ??= new \Symfony\Bridge\Twig\Extension\CsrfExtension()));
        $instance->addExtension(($container->privates['twig.extension.profiler'] ?? $container->load('getTwig_Extension_ProfilerService')));
        $instance->addExtension(($container->privates['twig.extension.trans'] ?? $container->load('getTwig_Extension_TransService')));
        $instance->addExtension(($container->privates['twig.extension.assets'] ?? $container->load('getTwig_Extension_AssetsService')));
        $instance->addExtension(($container->privates['twig.extension.routing'] ?? $container->load('getTwig_Extension_RoutingService')));
        $instance->addExtension(($container->privates['twig.extension.yaml'] ??= new \Symfony\Bridge\Twig\Extension\YamlExtension()));
        $instance->addExtension(($container->privates['twig.extension.expression'] ??= new \Symfony\Bridge\Twig\Extension\ExpressionExtension()));
        $instance->addExtension(($container->privates['twig.extension.htmlsanitizer'] ?? $container->load('getTwig_Extension_HtmlsanitizerService')));
        $instance->addExtension(($container->privates['twig.extension.httpkernel'] ??= new \Symfony\Bridge\Twig\Extension\HttpKernelExtension()));
        $instance->addExtension(($container->privates['twig.extension.httpfoundation'] ?? $container->load('getTwig_Extension_HttpfoundationService')));
        $instance->addExtension(($container->privates['twig.extension.serializer'] ??= new \Symfony\Bridge\Twig\Extension\SerializerExtension()));
        $instance->addExtension(($container->privates['twig.extension.logout_url'] ?? $container->load('getTwig_Extension_LogoutUrlService')));
        $instance->addExtension(($container->privates['twig.extension.security'] ?? $container->load('getTwig_Extension_SecurityService')));
        $instance->addExtension(($container->privates['twig.extension.debug'] ??= new \Twig\Extension\DebugExtension()));
        $instance->addExtension(($container->privates['doctrine.twig.doctrine_extension'] ??= new \Doctrine\Bundle\DoctrineBundle\Twig\DoctrineExtension()));
        $instance->addExtension(($container->privates['jms_serializer.twig_extension.runtime_serializer'] ??= new \JMS\Serializer\Twig\SerializerRuntimeExtension('jms_')));
        $instance->addExtension(($container->privates['sulu_contact.twig'] ?? $container->load('getSuluContact_TwigService')));
        $instance->addExtension(($container->privates['sulu_security.twig_extension.user'] ?? $container->load('getSuluSecurity_TwigExtension_UserService')));
        $instance->addExtension(($container->privates['sulu_website.twig.util'] ??= new \Sulu\Bundle\WebsiteBundle\Twig\Core\UtilTwigExtension()));
        $instance->addExtension(($container->privates['sulu_tag.twig_extension'] ?? $container->load('getSuluTag_TwigExtensionService')));
        $instance->addExtension(($container->privates['sulu_media.twig_extension.disposition_type'] ??= new \Sulu\Bundle\MediaBundle\Twig\DispositionTypeTwigExtension()));
        $instance->addExtension(($container->privates['sulu_media.twig_extension.media'] ?? $container->load('getSuluMedia_TwigExtension_MediaService')));
        $instance->addExtension(($container->privates['sulu_category.twig_extension'] ?? $container->load('getSuluCategory_TwigExtensionService')));
        $instance->addExtension(($container->privates['sulu_page.navigation_twig_extension'] ?? $container->load('getSuluPage_NavigationTwigExtensionService')));
        $instance->addExtension(($container->privates['sulu_page.content_path_twig_extension'] ?? $container->load('getSuluPage_ContentPathTwigExtensionService')));
        $instance->addExtension(($container->privates['sulu_page.page_twig_extension'] ?? $container->load('getSuluPage_PageTwigExtensionService')));
        $instance->addExtension(($container->privates['sulu_event.twig_extension'] ?? $container->load('getSuluEvent_TwigExtensionService')));
        $instance->addExtension(($container->privates['sulu_event.settings.twig_extension'] ?? $container->load('getSuluEvent_Settings_TwigExtensionService')));
        $instance->addExtension(($container->privates['sulu_event.calendar_twig_extension'] ?? $container->load('getSuluEvent_CalendarTwigExtensionService')));
        $instance->addExtension(($container->privates['sulu_event.social_share_extension'] ?? $container->load('getSuluEvent_SocialShareExtensionService')));
        $instance->addGlobal('app', ($container->privates['twig.app_variable'] ?? $container->load('getTwig_AppVariableService')));
        $instance->addRuntimeLoader(($container->privates['twig.runtime_loader'] ?? $container->load('getTwig_RuntimeLoaderService')));
        ($container->privates['twig.configurator.environment'] ?? $container->load('getTwig_Configurator_EnvironmentService'))->configure($instance);

        return $instance;
    }
}
