<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Loader_NativeFilesystemService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'twig.loader.native_filesystem' shared service.
     *
     * @return \Twig\Loader\FilesystemLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['twig.loader.native_filesystem'] = $instance = new \Twig\Loader\FilesystemLoader([], \dirname(__DIR__, 5));

        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\doctrine\\doctrine-bundle/templates', 'Doctrine');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\doctrine\\doctrine-bundle/templates', '!Doctrine');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\jms\\serializer-bundle/Resources/views', 'JMSSerializer');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\jms\\serializer-bundle/Resources/views', '!JMSSerializer');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\AdminBundle/Resources/views', 'SuluAdmin');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\AdminBundle/Resources/views', '!SuluAdmin');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\SecurityBundle/Resources/views', 'SuluSecurity');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\SecurityBundle/Resources/views', '!SuluSecurity');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\WebsiteBundle/Resources/views', 'SuluWebsite');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\WebsiteBundle/Resources/views', '!SuluWebsite');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\TestBundle/Resources/views', 'SuluTest');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\TestBundle/Resources/views', '!SuluTest');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\PreviewBundle/Resources/views', 'SuluPreview');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\PreviewBundle/Resources/views', '!SuluPreview');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\AudienceTargetingBundle/Resources/views', 'SuluAudienceTargeting');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\AudienceTargetingBundle/Resources/views', '!SuluAudienceTargeting');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\symfony\\security-bundle/Resources/views', 'Security');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\symfony\\security-bundle/Resources/views', '!Security');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\src/Resources/views', 'SuluEvent');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\src/Resources/views', '!SuluEvent');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\symfony\\twig-bridge/Resources/views/Email', 'email');
        $instance->addPath('D:\\Projects\\Bundles\\SuluEventBundle\\vendor\\symfony\\twig-bridge/Resources/views/Email', '!email');

        return $instance;
    }
}
