<?php

namespace ContainerHU8k9z3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUuid_FactoryService extends Manuxi_SuluEventBundle_Tests_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'uuid.factory' shared service.
     *
     * @return \Symfony\Component\Uid\Factory\UuidFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['uuid.factory'] = new \Symfony\Component\Uid\Factory\UuidFactory(7, 7, 5, 'Symfony\\Component\\Uid\\UuidV4', NULL, NULL);
    }
}
