services:
    # Admin Controllers
    Manuxi\SuluEventBundle\Controller\Admin\EventController:
        class: Manuxi\SuluEventBundle\Controller\Admin\EventController
        arguments:
            - '@fos_rest.view_handler.default'
            - '@security.token_storage'
            - '@sulu_core.list_builder.field_descriptor_factory'
            - '@sulu_core.doctrine_list_builder_factory'
            - '@sulu_core.rest_helper'
            - '@sulu_content.content_manager'
            - '@doctrine.orm.entity_manager'
            - '@Manuxi\SuluEventBundle\ListBuilder\DoctrineListRepresentationFactory'
            - '@sulu_activity.domain_event_collector'
            - '@sulu_trash.trash_manager'
            - '@sulu_content.content_workflow'
        tags:
            - { name: controller.service_arguments }
            - { name: sulu.context, context: admin }
        public: true

    Manuxi\SuluEventBundle\Controller\Admin\LocationController:
        class: Manuxi\SuluEventBundle\Controller\Admin\LocationController
        arguments:
            - '@Manuxi\SuluEventBundle\Repository\LocationRepository'
            - '@doctrine.orm.entity_manager'
            - '@sulu_trash.trash_manager'
            - '@sulu_core.list_builder.field_descriptor_factory'
            - '@sulu_core.doctrine_list_builder_factory'
            - '@sulu_core.rest_helper'
            - '@fos_rest.view_handler.default'
            - '@security.token_storage'
        tags:
            - { name: controller.service_arguments }
            - { name: sulu.context, context: admin }
        public: true

    Manuxi\SuluEventBundle\Controller\Admin\SettingsController:
        class: Manuxi\SuluEventBundle\Controller\Admin\SettingsController
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sulu_activity.domain_event_collector'
            - '@fos_rest.view_handler.default'
            - '@security.token_storage'
        tags:
            - { name: controller.service_arguments }
            - { name: sulu.context, context: admin }
        public: true

    # Website Controller
    Manuxi\SuluEventBundle\Controller\Website\EventController:
        class: Manuxi\SuluEventBundle\Controller\Website\EventController
        arguments:
            - '@twig'
            - '@sulu_website.resolver.template_attribute'
            - '@sulu_route.route_repository'
            - '@sulu_core.webspace.webspace_manager'
            - '@request_stack'
            - '@sulu_content.content_aggregator'
        tags:
            - { name: controller.service_arguments }
            - { name: sulu.context, context: website }

    # Feed Services
    Manuxi\SuluEventBundle\Controller\Website\FeedController:
        class: Manuxi\SuluEventBundle\Controller\Website\FeedController
        public: true
        arguments:
            - '@Manuxi\SuluEventBundle\Repository\EventRepository'
            - '@router'
            - '@sulu_content.content_aggregator'
        tags:
            - { name: controller.service_arguments }
            - { name: sulu.context, context: website }
        calls:
            - [ setContainer, [ '@service_container' ] ]

    # Calendar Services
    Manuxi\SuluEventBundle\Controller\Website\CalendarApiController:
        class: Manuxi\SuluEventBundle\Controller\Website\CalendarApiController
        public: true
        arguments:
            - '@Manuxi\SuluEventBundle\Repository\EventRepository'
            - '@sulu_event.type_selection'
            - '@sulu_content.content_aggregator'
        tags:
            - { name: controller.service_arguments }
            - { name: sulu.context, context: website }
        calls:
            - [ setContainer, [ '@service_container' ] ]