# Calendar API for FullCalendar
sulu_event.api.calendar:
    path: /api/events/calendar/{_locale}
    controller: Manuxi\SuluEventBundle\Controller\Website\CalendarApiController::calendarAction
    methods: [GET]
    defaults:
        _locale: en

# RSS Feed
sulu_event.feed:
    path: /events/feed.{_locale}.{_format}
    controller: Manuxi\SuluEventBundle\Controller\Website\FeedController::feedAction
    methods: [GET]
    defaults:
        _locale: en
        _format: rss
    requirements:
        _format: rss|atom

# iCal Single Event
sulu_event.ical_single:
    path: /events/{id}/download.{_locale}.ics
    controller: Manuxi\SuluEventBundle\Controller\Website\ICalController::singleAction
    methods: [GET]
    defaults:
        _locale: en
    requirements:
        id: \d+

# iCal Calendar-Feed
sulu_event.ical_feed:
    path: /events/calendar.{_locale}.ics
    controller: Manuxi\SuluEventBundle\Controller\Website\ICalController::feedAction
    methods: [GET]
    defaults:
        _locale: en