app_events_api:
    type: attribute
    resource: Manuxi\SuluEventBundle\Controller\Admin\EventController
    options:
        expose: true
app_locations_api:
    type: attribute
    resource: Manuxi\SuluEventBundle\Controller\Admin\LocationController
    options:
        expose: true
sulu_event_settings_api:
    type: attribute
    resource: Manuxi\SuluEventBundle\Controller\Admin\SettingsController
    options:
        expose: true