services:

    # Admin Classes
    sulu_event.admin.event:
        class: Manuxi\SuluEventBundle\Admin\EventAdmin
        arguments:
            - '@sulu_admin.view_builder_factory'
            - '@sulu_content.content_view_builder_factory'
            - '@sulu_security.security_checker'
            - '@sulu.core.localization_manager'
            - '@sulu_activity.activity_list_view_builder_factory'
        tags:
            - { name: sulu.admin }
            - { name: sulu.context, context: admin }

    sulu_event.admin.location:
        class: Manuxi\SuluEventBundle\Admin\LocationAdmin
        arguments:
            - '@sulu_admin.view_builder_factory'
            - '@sulu_security.security_checker'
        tags:
            - { name: sulu.admin }
            - { name: sulu.context, context: admin }

    sulu_event.admin.settings:
        class: Manuxi\SuluEventBundle\Admin\SettingsAdmin
        arguments:
            - '@sulu_admin.view_builder_factory'
            - '@sulu_security.security_checker'
        tags:
            - { name: sulu.admin }
            - { name: sulu.context, context: admin }

    # Repositories
    Manuxi\SuluEventBundle\Repository\EventRepository:
        class: Manuxi\SuluEventBundle\Repository\EventRepository
        arguments:
            - '@doctrine'
            - '@sulu_content.dimension_content_query_enhancer'
        public: true
        tags:
            - { name: doctrine.repository_service }

    Manuxi\SuluEventBundle\Repository\EventDimensionContentRepository:
        class: Manuxi\SuluEventBundle\Repository\EventDimensionContentRepository
        arguments:
            - '@doctrine'
        public: true
        tags:
            - { name: doctrine.repository_service }

    Manuxi\SuluEventBundle\Repository\LocationRepository:
        class: Manuxi\SuluEventBundle\Repository\LocationRepository
        arguments:
            - '@doctrine'
        public: true
        tags:
            - { name: doctrine.repository_service }

    Manuxi\SuluEventBundle\ListBuilder\DoctrineListRepresentationFactory:
        class: Manuxi\SuluEventBundle\ListBuilder\DoctrineListRepresentationFactory
        arguments:
            - '@sulu_core.rest_helper'
            - '@sulu_core.list_rest_helper'
            - '@sulu_core.doctrine_list_builder_factory'
            - '@sulu_core.list_builder.field_descriptor_factory'
            - '@sulu_core.webspace.webspace_manager'
            - '@Manuxi\SuluEventBundle\Repository\EventDimensionContentRepository'
            - '@sulu_media.media_manager'
            - '@sulu_event.type_selection'
            - '@translator.default'
            - '%sulu_event.list_date_format%'

    # Routing
    Manuxi\SuluEventBundle\Routing\EventRouteDefaultsProvider:
        class: Manuxi\SuluEventBundle\Routing\EventRouteDefaultsProvider
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sulu_content.content_aggregator'
            - '@sulu_admin.metadata_provider_registry'
            - '@sulu_http_cache.cache_lifetime.resolver'
        public: true
        tags:
            - { name: sulu_route.route_defaults_provider, resource-key: events, resource_key: events }

    # SmartContent Provider
    sulu_event.event_smart_content_provider:
        class: Manuxi\SuluEventBundle\Content\EventSmartContentProvider
        arguments:
            - '@sulu_content.dimension_content_query_enhancer'
            - '@sulu_admin.smart_content_query_enhancer'
            - '@doctrine.orm.entity_manager'
            - '@translator.default'
            - '%sulu_event.types%'
        tags:
            - { name: sulu_content.smart_content_provider, type: events }

    # Teaser Provider
    sulu_event.event_teaser_provider:
        class: Manuxi\SuluEventBundle\Teaser\EventTeaserProvider
        public: true
        arguments:
            - '@Manuxi\SuluEventBundle\Repository\EventRepository'
            - '@sulu_content.content_aggregator'
            - '@sulu_content.content_enhancer'
            - '@translator'
        tags:
            - { name: sulu.teaser.provider, alias: events }

    # Type Select Service
    sulu_event.type_selection:
        class: Manuxi\SuluEventBundle\Service\EventTypeSelect
        arguments:
            - '@translator'
            - '%sulu_event.types%'
            - '%sulu_event.default_type%'
        public: true

    # Country Code Select Service
    sulu_event.country_code_select:
        class: Manuxi\SuluEventBundle\Service\CountryCodeSelect
        public: true

    # LocationPremises Service
    sulu_event.location_premises_selection:
        class: Manuxi\SuluEventBundle\Service\LocationPremisesSelection
        arguments:
            - '@Manuxi\SuluEventBundle\Repository\LocationRepository'
        public: true

    # Property Resolvers
    sulu_event.property_resolver.single_event_selection:
        class: Manuxi\SuluEventBundle\Content\PropertyResolver\SingleEventSelectionPropertyResolver
        tags:
            - { name: sulu_content.property_resolver }

    sulu_event.property_resolver.event_selection:
        class: Manuxi\SuluEventBundle\Content\PropertyResolver\EventSelectionPropertyResolver
        tags:
            - { name: sulu_content.property_resolver }

    sulu_event.property_resolver.event_calendar:
        class: Manuxi\SuluEventBundle\Content\PropertyResolver\EventCalendarPropertyResolver
        tags:
            - { name: sulu_content.property_resolver }

    sulu_event.property_resolver.single_location_selection:
        class: Manuxi\SuluEventBundle\Content\PropertyResolver\SingleLocationSelectionPropertyResolver
        tags:
            - { name: sulu_content.property_resolver, type: 'single_location_selection' }

    # Resource Loader
    sulu_event.resource_loader.event:
        class: Manuxi\SuluEventBundle\Content\ResourceLoader\EventResourceLoader
        arguments:
            - '@Manuxi\SuluEventBundle\Repository\EventRepository'
        tags:
            - { name: sulu_content.resource_loader }

    Manuxi\SuluEventBundle\Content\ResourceLoader\LocationResourceLoader:
        class: Manuxi\SuluEventBundle\Content\ResourceLoader\LocationResourceLoader
        arguments:
            - '@Manuxi\SuluEventBundle\Repository\LocationRepository'
        tags:
            - { name: sulu_content.resource_loader, type: 'locations' }

    # Property Merger
    sulu_event.event_unlocalized_fields_merger:
        class: Manuxi\SuluEventBundle\Content\Merger\EventUnlocalizedFieldsMerger
        tags:
            - { name: sulu_content.merger }

    # DataMapper for unlocalized event
    sulu_event.event_unlocalized_data_mapper:
        class: Manuxi\SuluEventBundle\Content\DataMapper\EventUnlocalizedDataMapper
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: sulu_content.data_mapper }

    Manuxi\SuluEventBundle\Content\DataMapper\LocationDataMapper:
        class: Manuxi\SuluEventBundle\Content\DataMapper\LocationDataMapper
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: sulu_content.data_mapper, priority: 10 }

    # DataMapper for automatically setting author to current user's contact when creating events
    Manuxi\SuluEventBundle\Content\DataMapper\AutoAuthorDataMapper:
        class: Manuxi\SuluEventBundle\Content\DataMapper\AutoAuthorDataMapper
        arguments:
            - '@security.helper'
        tags:
            - { name: sulu_content.data_mapper, priority: -50 }

    # Preview Object Provider
    sulu_event.preview_object_provider:
        class: Manuxi\SuluEventBundle\Preview\EventObjectProvider
        arguments:
            - '@Manuxi\SuluEventBundle\Repository\EventRepository'
            - '@sulu_content.content_aggregator'
        tags:
            - { name: sulu.context, context: admin }
            - { name: sulu_preview.object_provider, provider-key: events }

    sulu_event.recurrence_generator:
        class: Manuxi\SuluEventBundle\Service\RecurrenceGenerator

    sulu_event.command.generate_recurring:
        class: Manuxi\SuluEventBundle\Command\GenerateRecurringEventsCommand
        arguments:
            - '@Manuxi\SuluEventBundle\Repository\EventRepository'
            - '@sulu_event.recurrence_generator'
            - '@doctrine.orm.entity_manager'
            - '@sulu_content.content_manager'
        tags:
            - { name: console.command }

    sulu_event.social_share_generator:
        class: Manuxi\SuluEventBundle\Service\SocialShareGenerator
        arguments:
            - '@sulu_content.content_aggregator'
            - '@sulu_media.media_manager'

    # Reference refresher
    Manuxi\SuluEventBundle\Reference\EventReferenceRefresher:
        class: Manuxi\SuluEventBundle\Reference\EventReferenceRefresher
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Sulu\Bundle\ReferenceBundle\Domain\Repository\ReferenceRepositoryInterface'
            - '@sulu_content.content_view_resolver'
            - '@sulu_content.content_merger'
        tags:
            - { name: sulu_reference.refresher }

    # Sitemap Provider
    sulu_event.sitemap_provider:
        class: Manuxi\SuluEventBundle\Sitemap\EventSitemapProvider
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sulu_core.webspace.webspace_manager'
            - '%kernel.environment%'
        tags:
            - { name: sulu.sitemap.provider }

    # Search Providers
    sulu_event.search.admin_provider:
        class: Manuxi\SuluEventBundle\Search\EventAdminSearchProvider
        arguments:
            - '@Manuxi\SuluEventBundle\Repository\EventRepository'
            - '@sulu_core.webspace.webspace_manager'
            - '@sulu_content.content_aggregator'
        tags:
            - { name: cmsig_seal.reindex_provider }

    sulu_event.search.website_provider:
        class: Manuxi\SuluEventBundle\Search\EventWebsiteSearchProvider
        arguments:
            - '@Manuxi\SuluEventBundle\Repository\EventRepository'
            - '@sulu_core.webspace.webspace_manager'
            - '@sulu_content.content_aggregator'
        tags:
            - { name: cmsig_seal.reindex_provider }

    sulu_event.search.listener:
        class: Manuxi\SuluEventBundle\Search\EventSearchListener
        arguments:
            - '@cmsig_seal.engine.default'
            - '@sulu_core.webspace.webspace_manager'
            - '@sulu_content.content_aggregator'
        tags:
            - { name: kernel.event_subscriber }

    # Link Provider
    sulu_event.link_provider:
        class: Manuxi\SuluEventBundle\Link\LinkProvider
        arguments:
            - '@sulu_content.content_aggregator'
            - '@Manuxi\SuluEventBundle\Repository\EventRepository'
            - '@translator.default'
        tags:
            - { name: sulu.link.provider, alias: event }

    # Event Mapper
    sulu_event.event_mapper:
        class: Manuxi\SuluEventBundle\Application\Mapper\EventMapper
        arguments:
            - '@sulu_content.content_manager'
        tags:
            - { name: sulu_event.event_mapper }

    # Trash Handler
    sulu_event.trash_item_handler:
        class: Manuxi\SuluEventBundle\Trash\EventTrashItemHandler
        arguments:
            - '@sulu_trash.trash_item_repository'
            - '@Manuxi\SuluEventBundle\Repository\EventRepository'
            - '@sulu_content.content_normalizer'
            - '@sulu_content.content_merger'
            - !tagged_iterator sulu_event.event_mapper
            - '@sulu_activity.domain_event_collector'
        tags:
            - { name: sulu_trash.store_trash_item_handler }
            - { name: sulu_trash.restore_trash_item_handler }
            - { name: sulu_trash.restore_configuration_provider }

    Manuxi\SuluEventBundle\Trash\LocationTrashItemHandler:
        class: Manuxi\SuluEventBundle\Trash\LocationTrashItemHandler
        arguments:
            - '@sulu_trash.trash_item_repository'
            - '@doctrine.orm.entity_manager'
            - '@sulu_trash.doctrine_restore_helper'
            - '@sulu_activity.domain_event_collector'
        tags:
            - { name: sulu_trash.store_trash_item_handler, alias: locations }
            - { name: sulu_trash.restore_trash_item_handler, alias: locations }
            - { name: sulu_trash.restore_configuration_provider }

    # Twig Extensions
    sulu_event.twig_extension:
        class: Manuxi\SuluEventBundle\Twig\EventTwigExtension
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sulu_content.content_aggregator'
            - '@sulu_content.content_resolver'
            - '@sulu_core.webspace.request_analyzer'
        tags:
            - { name: twig.extension }

    sulu_event.settings.twig_extension:
        class: Manuxi\SuluEventBundle\Twig\EventSettingsTwigExtension
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: twig.extension }

    sulu_event.calendar_twig_extension:
        class: Manuxi\SuluEventBundle\Twig\EventCalendarTwigExtension
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sulu_content.content_aggregator'
            - '@sulu_content.content_resolver'
            - '@sulu_core.webspace.request_analyzer'
        tags:
            - { name: twig.extension }

    # Normalizer
    sulu_event.event_normalizer:
        class: Manuxi\SuluEventBundle\Content\Normalizer\EventNormalizer
        arguments:
            - '@translator'
            - '@sulu_event.type_selection'
        tags:
            - { name: sulu_content.normalizer }
